./gen.sh 'Anonymice Complete Mono'
./gen.sh 'Anonymice Complete'
./gen.sh 'Anonymice'
./gen.sh 'Anonymice Complete'
./gen.sh 'Anonymice'
./gen.sh 'Anonymice'
./gen.sh 'Anonymice Mono Complete Mono'
./gen.sh 'Anonymice Mono Complete'
./gen.sh 'Anonymice Mono'
./gen.sh 'Anonymice Mono Complete'
./gen.sh 'Anonymice Mono'
./gen.sh 'Anonymice'
./gen.sh 'Arimo Bold Complete Mono'
./gen.sh 'Arimo Bold Complete'
./gen.sh 'Arimo Bold'
./gen.sh 'Arimo Bold Complete'
./gen.sh 'Arimo Bold'
./gen.sh 'Arimo'
./gen.sh 'Arimo Bold Italic Complete Mono'
./gen.sh 'Arimo Bold Italic Complete'
./gen.sh 'Arimo Bold Italic'
./gen.sh 'Arimo Bold Italic Complete'
./gen.sh 'Arimo Bold Italic'
./gen.sh 'Arimo Bold'
./gen.sh 'Arimo Complete Mono'
./gen.sh 'Arimo Complete'
./gen.sh 'Arimo'
./gen.sh 'Arimo Complete'
./gen.sh 'Arimo'
./gen.sh 'Arimo'
./gen.sh 'Arimo Italic Complete Mono'
./gen.sh 'Arimo Italic Complete'
./gen.sh 'Arimo Italic'
./gen.sh 'Arimo Italic Complete'
./gen.sh 'Arimo Italic'
./gen.sh 'Arimo'
./gen.sh 'Bitstream Vera Sans Mono Bold Complete Mono'
./gen.sh 'Bitstream Vera Sans Mono Bold Complete'
./gen.sh 'Bitstream Vera Sans Mono Bold'
./gen.sh 'Bitstream Vera Sans Mono Bold Complete'
./gen.sh 'Bitstream Vera Sans Mono Bold'
./gen.sh 'Bitstream Vera Sans Mono'
./gen.sh 'Bitstream Vera Sans Mono Bold Mono Complete Mono'
./gen.sh 'Bitstream Vera Sans Mono Bold Mono Complete'
./gen.sh 'Bitstream Vera Sans Mono Bold Mono'
./gen.sh 'Bitstream Vera Sans Mono Bold Mono Complete'
./gen.sh 'Bitstream Vera Sans Mono Bold Mono'
./gen.sh 'Bitstream Vera Sans Mono Bold'
./gen.sh 'Bitstream Vera Sans Mono Bold Oblique Complete Mono'
./gen.sh 'Bitstream Vera Sans Mono Bold Oblique Complete'
./gen.sh 'Bitstream Vera Sans Mono Bold Oblique'
./gen.sh 'Bitstream Vera Sans Mono Bold Oblique Complete'
./gen.sh 'Bitstream Vera Sans Mono Bold Oblique'
./gen.sh 'Bitstream Vera Sans Mono Bold'
./gen.sh 'Bitstream Vera Sans Mono Bold Oblique Mono Complete Mono'
./gen.sh 'Bitstream Vera Sans Mono Bold Oblique Mono Complete'
./gen.sh 'Bitstream Vera Sans Mono Bold Oblique Mono'
./gen.sh 'Bitstream Vera Sans Mono Bold Oblique Mono Complete'
./gen.sh 'Bitstream Vera Sans Mono Bold Oblique Mono'
./gen.sh 'Bitstream Vera Sans Mono Bold Oblique'
./gen.sh 'Bitstream Vera Sans Mono Complete Mono'
./gen.sh 'Bitstream Vera Sans Mono Complete'
./gen.sh 'Bitstream Vera Sans Mono'
./gen.sh 'Bitstream Vera Sans Mono Complete'
./gen.sh 'Bitstream Vera Sans Mono'
./gen.sh 'Bitstream Vera Sans'
./gen.sh 'Bitstream Vera Sans Mono Mono Complete Mono'
./gen.sh 'Bitstream Vera Sans Mono Mono Complete'
./gen.sh 'Bitstream Vera Sans Mono Mono'
./gen.sh 'Bitstream Vera Sans Mono Mono Complete'
./gen.sh 'Bitstream Vera Sans Mono Mono'
./gen.sh 'Bitstream Vera Sans Mono'
./gen.sh 'Bitstream Vera Sans Mono Oblique Complete Mono'
./gen.sh 'Bitstream Vera Sans Mono Oblique Complete'
./gen.sh 'Bitstream Vera Sans Mono Oblique'
./gen.sh 'Bitstream Vera Sans Mono Oblique Complete'
./gen.sh 'Bitstream Vera Sans Mono Oblique'
./gen.sh 'Bitstream Vera Sans Mono'
./gen.sh 'Bitstream Vera Sans Mono Oblique Mono Complete Mono'
./gen.sh 'Bitstream Vera Sans Mono Oblique Mono Complete'
./gen.sh 'Bitstream Vera Sans Mono Oblique Mono'
./gen.sh 'Bitstream Vera Sans Mono Oblique Mono Complete'
./gen.sh 'Bitstream Vera Sans Mono Oblique Mono'
./gen.sh 'Bitstream Vera Sans Mono Oblique'
./gen.sh 'Cousine Bold Complete Mono'
./gen.sh 'Cousine Bold Complete'
./gen.sh 'Cousine Bold'
./gen.sh 'Cousine Bold Complete'
./gen.sh 'Cousine Bold'
./gen.sh 'Cousine'
./gen.sh 'Cousine Bold Italic Complete Mono'
./gen.sh 'Cousine Bold Italic Complete'
./gen.sh 'Cousine Bold Italic'
./gen.sh 'Cousine Bold Italic Complete'
./gen.sh 'Cousine Bold Italic'
./gen.sh 'Cousine Bold'
./gen.sh 'Cousine Complete Mono'
./gen.sh 'Cousine Complete'
./gen.sh 'Cousine'
./gen.sh 'Cousine Complete'
./gen.sh 'Cousine'
./gen.sh 'Cousine'
./gen.sh 'Cousine Italic Complete Mono'
./gen.sh 'Cousine Italic Complete'
./gen.sh 'Cousine Italic'
./gen.sh 'Cousine Italic Complete'
./gen.sh 'Cousine Italic'
./gen.sh 'Cousine'
./gen.sh 'DejaVu Sans Mono Bold Complete Mono'
./gen.sh 'DejaVu Sans Mono Bold Complete'
./gen.sh 'DejaVu Sans Mono Bold'
./gen.sh 'DejaVu Sans Mono Bold Complete'
./gen.sh 'DejaVu Sans Mono Bold'
./gen.sh 'DejaVu Sans Mono'
./gen.sh 'DejaVu Sans Mono Bold Mono Complete Mono'
./gen.sh 'DejaVu Sans Mono Bold Mono Complete'
./gen.sh 'DejaVu Sans Mono Bold Mono'
./gen.sh 'DejaVu Sans Mono Bold Mono Complete'
./gen.sh 'DejaVu Sans Mono Bold Mono'
./gen.sh 'DejaVu Sans Mono Bold'
./gen.sh 'DejaVu Sans Mono Bold Oblique Complete Mono'
./gen.sh 'DejaVu Sans Mono Bold Oblique Complete'
./gen.sh 'DejaVu Sans Mono Bold Oblique'
./gen.sh 'DejaVu Sans Mono Bold Oblique Complete'
./gen.sh 'DejaVu Sans Mono Bold Oblique'
./gen.sh 'DejaVu Sans Mono Bold'
./gen.sh 'DejaVu Sans Mono Bold Oblique Mono Complete Mono'
./gen.sh 'DejaVu Sans Mono Bold Oblique Mono Complete'
./gen.sh 'DejaVu Sans Mono Bold Oblique Mono'
./gen.sh 'DejaVu Sans Mono Bold Oblique Mono Complete'
./gen.sh 'DejaVu Sans Mono Bold Oblique Mono'
./gen.sh 'DejaVu Sans Mono Bold Oblique'
./gen.sh 'DejaVu Sans Mono Complete Mono'
./gen.sh 'DejaVu Sans Mono Complete'
./gen.sh 'DejaVu Sans Mono'
./gen.sh 'DejaVu Sans Mono Complete'
./gen.sh 'DejaVu Sans Mono'
./gen.sh 'DejaVu Sans'
./gen.sh 'DejaVu Sans Mono Mono Complete Mono'
./gen.sh 'DejaVu Sans Mono Mono Complete'
./gen.sh 'DejaVu Sans Mono Mono'
./gen.sh 'DejaVu Sans Mono Mono Complete'
./gen.sh 'DejaVu Sans Mono Mono'
./gen.sh 'DejaVu Sans Mono'
./gen.sh 'DejaVu Sans Mono Oblique Complete Mono'
./gen.sh 'DejaVu Sans Mono Oblique Complete'
./gen.sh 'DejaVu Sans Mono Oblique'
./gen.sh 'DejaVu Sans Mono Oblique Complete'
./gen.sh 'DejaVu Sans Mono Oblique'
./gen.sh 'DejaVu Sans Mono'
./gen.sh 'DejaVu Sans Mono Oblique Mono Complete Mono'
./gen.sh 'DejaVu Sans Mono Oblique Mono Complete'
./gen.sh 'DejaVu Sans Mono Oblique Mono'
./gen.sh 'DejaVu Sans Mono Oblique Mono Complete'
./gen.sh 'DejaVu Sans Mono Oblique Mono'
./gen.sh 'DejaVu Sans Mono Oblique'
./gen.sh 'DejaVuSansMonoWithOcticons Complete Mono'
./gen.sh 'DejaVuSansMonoWithOcticons Complete'
./gen.sh 'DejaVuSansMonoWithOcticons'
./gen.sh 'DejaVuSansMonoWithOcticons Complete'
./gen.sh 'DejaVuSansMonoWithOcticons'
./gen.sh 'DejaVuSansMonoWithOcticons'
./gen.sh 'Droid Sans Mono Dotted Complete Mono'
./gen.sh 'Droid Sans Mono Dotted Complete'
./gen.sh 'Droid Sans Mono Dotted'
./gen.sh 'Droid Sans Mono Dotted Complete'
./gen.sh 'Droid Sans Mono Dotted'
./gen.sh 'Droid Sans Mono'
./gen.sh 'Droid Sans Mono Slashed Complete Mono'
./gen.sh 'Droid Sans Mono Slashed Complete'
./gen.sh 'Droid Sans Mono Slashed'
./gen.sh 'Droid Sans Mono Slashed Complete'
./gen.sh 'Droid Sans Mono Slashed'
./gen.sh 'Droid Sans Mono'
./gen.sh 'Fixedsys Excelsior 3.01 Complete Mono'
./gen.sh 'Fixedsys Excelsior 3.01 Complete'
./gen.sh 'Fixedsys Excelsior 3.01'
./gen.sh 'Fixedsys Excelsior 3.01 Complete'
./gen.sh 'Fixedsys Excelsior 3.01'
./gen.sh 'Fixedsys Excelsior'
./gen.sh 'Hack Bold Complete Mono'
./gen.sh 'Hack Bold Complete'
./gen.sh 'Hack Bold'
./gen.sh 'Hack Bold Complete'
./gen.sh 'Hack Bold'
./gen.sh 'Hack'
./gen.sh 'Hack Bold Italic Complete Mono'
./gen.sh 'Hack Bold Italic Complete'
./gen.sh 'Hack Bold Italic'
./gen.sh 'Hack Bold Italic Complete'
./gen.sh 'Hack Bold Italic'
./gen.sh 'Hack Bold'
./gen.sh 'Hack Italic Complete Mono'
./gen.sh 'Hack Italic Complete'
./gen.sh 'Hack Italic'
./gen.sh 'Hack Italic Complete'
./gen.sh 'Hack Italic'
./gen.sh 'Hack'
./gen.sh 'Hack Regular Complete Mono'
./gen.sh 'Hack Regular Complete'
./gen.sh 'Hack Regular'
./gen.sh 'Hack Regular Complete'
./gen.sh 'Hack Regular'
./gen.sh 'Hack'
./gen.sh 'HackWithOcticons Complete Mono'
./gen.sh 'HackWithOcticons Complete'
./gen.sh 'HackWithOcticons'
./gen.sh 'HackWithOcticons Complete'
./gen.sh 'HackWithOcticons'
./gen.sh 'HackWithOcticons'
./gen.sh 'Heavy Data Complete Mono'
./gen.sh 'Heavy Data Complete'
./gen.sh 'Heavy Data'
./gen.sh 'Heavy Data Complete'
./gen.sh 'Heavy Data'
./gen.sh 'Heavy'
./gen.sh 'Heavy Data Mono Complete Mono'
./gen.sh 'Heavy Data Mono Complete'
./gen.sh 'Heavy Data Mono'
./gen.sh 'Heavy Data Mono Complete'
./gen.sh 'Heavy Data Mono'
./gen.sh 'Heavy Data'
./gen.sh 'InputMono Black Complete Mono'
./gen.sh 'InputMono Black Complete'
./gen.sh 'InputMono Black'
./gen.sh 'InputMono Black Complete'
./gen.sh 'InputMono Black'
./gen.sh 'InputMono'
./gen.sh 'InputMono BlackIta Complete Mono'
./gen.sh 'InputMono BlackIta Complete'
./gen.sh 'InputMono BlackIta'
./gen.sh 'InputMono BlackIta Complete'
./gen.sh 'InputMono BlackIta'
./gen.sh 'InputMono'
./gen.sh 'InputMono Bold Complete Mono'
./gen.sh 'InputMono Bold Complete'
./gen.sh 'InputMono Bold'
./gen.sh 'InputMono Bold Complete'
./gen.sh 'InputMono Bold'
./gen.sh 'InputMono'
./gen.sh 'InputMono BoldIta Complete Mono'
./gen.sh 'InputMono BoldIta Complete'
./gen.sh 'InputMono BoldIta'
./gen.sh 'InputMono BoldIta Complete'
./gen.sh 'InputMono BoldIta'
./gen.sh 'InputMono'
./gen.sh 'InputMono Complete Mono'
./gen.sh 'InputMono Complete'
./gen.sh 'InputMono'
./gen.sh 'InputMono Complete'
./gen.sh 'InputMono'
./gen.sh 'InputMono'
./gen.sh 'InputMono ExLight Complete Mono'
./gen.sh 'InputMono ExLight Complete'
./gen.sh 'InputMono ExLight'
./gen.sh 'InputMono ExLight Complete'
./gen.sh 'InputMono ExLight'
./gen.sh 'InputMono'
./gen.sh 'InputMono ExLightIta Complete Mono'
./gen.sh 'InputMono ExLightIta Complete'
./gen.sh 'InputMono ExLightIta'
./gen.sh 'InputMono ExLightIta Complete'
./gen.sh 'InputMono ExLightIta'
./gen.sh 'InputMono'
./gen.sh 'InputMono Italic Complete Mono'
./gen.sh 'InputMono Italic Complete'
./gen.sh 'InputMono Italic'
./gen.sh 'InputMono Italic Complete'
./gen.sh 'InputMono Italic'
./gen.sh 'InputMono'
./gen.sh 'InputMono Light Complete Mono'
./gen.sh 'InputMono Light Complete'
./gen.sh 'InputMono Light'
./gen.sh 'InputMono Light Complete'
./gen.sh 'InputMono Light'
./gen.sh 'InputMono'
./gen.sh 'InputMono LightIta Complete Mono'
./gen.sh 'InputMono LightIta Complete'
./gen.sh 'InputMono LightIta'
./gen.sh 'InputMono LightIta Complete'
./gen.sh 'InputMono LightIta'
./gen.sh 'InputMono'
./gen.sh 'InputMono Medium Complete Mono'
./gen.sh 'InputMono Medium Complete'
./gen.sh 'InputMono Medium'
./gen.sh 'InputMono Medium Complete'
./gen.sh 'InputMono Medium'
./gen.sh 'InputMono'
./gen.sh 'InputMono MediumIta Complete Mono'
./gen.sh 'InputMono MediumIta Complete'
./gen.sh 'InputMono MediumIta'
./gen.sh 'InputMono MediumIta Complete'
./gen.sh 'InputMono MediumIta'
./gen.sh 'InputMono'
./gen.sh 'InputMono Thin Complete Mono'
./gen.sh 'InputMono Thin Complete'
./gen.sh 'InputMono Thin'
./gen.sh 'InputMono Thin Complete'
./gen.sh 'InputMono Thin'
./gen.sh 'InputMono'
./gen.sh 'InputMono ThinIta Complete Mono'
./gen.sh 'InputMono ThinIta Complete'
./gen.sh 'InputMono ThinIta'
./gen.sh 'InputMono ThinIta Complete'
./gen.sh 'InputMono ThinIta'
./gen.sh 'InputMono'
./gen.sh 'InputMonoCompressed Black Complete Mono'
./gen.sh 'InputMonoCompressed Black Complete'
./gen.sh 'InputMonoCompressed Black'
./gen.sh 'InputMonoCompressed Black Complete'
./gen.sh 'InputMonoCompressed Black'
./gen.sh 'InputMonoCompressed'
./gen.sh 'InputMonoCompressed BlackIta Complete Mono'
./gen.sh 'InputMonoCompressed BlackIta Complete'
./gen.sh 'InputMonoCompressed BlackIta'
./gen.sh 'InputMonoCompressed BlackIta Complete'
./gen.sh 'InputMonoCompressed BlackIta'
./gen.sh 'InputMonoCompressed'
./gen.sh 'InputMonoCompressed Bold Complete Mono'
./gen.sh 'InputMonoCompressed Bold Complete'
./gen.sh 'InputMonoCompressed Bold'
./gen.sh 'InputMonoCompressed Bold Complete'
./gen.sh 'InputMonoCompressed Bold'
./gen.sh 'InputMonoCompressed'
./gen.sh 'InputMonoCompressed BoldIta Complete Mono'
./gen.sh 'InputMonoCompressed BoldIta Complete'
./gen.sh 'InputMonoCompressed BoldIta'
./gen.sh 'InputMonoCompressed BoldIta Complete'
./gen.sh 'InputMonoCompressed BoldIta'
./gen.sh 'InputMonoCompressed'
./gen.sh 'InputMonoCompressed Complete Mono'
./gen.sh 'InputMonoCompressed Complete'
./gen.sh 'InputMonoCompressed'
./gen.sh 'InputMonoCompressed Complete'
./gen.sh 'InputMonoCompressed'
./gen.sh 'InputMonoCompressed'
./gen.sh 'InputMonoCompressed ExLight Complete Mono'
./gen.sh 'InputMonoCompressed ExLight Complete'
./gen.sh 'InputMonoCompressed ExLight'
./gen.sh 'InputMonoCompressed ExLight Complete'
./gen.sh 'InputMonoCompressed ExLight'
./gen.sh 'InputMonoCompressed'
./gen.sh 'InputMonoCompressed ExLightIta Complete Mono'
./gen.sh 'InputMonoCompressed ExLightIta Complete'
./gen.sh 'InputMonoCompressed ExLightIta'
./gen.sh 'InputMonoCompressed ExLightIta Complete'
./gen.sh 'InputMonoCompressed ExLightIta'
./gen.sh 'InputMonoCompressed'
./gen.sh 'InputMonoCompressed Italic Complete Mono'
./gen.sh 'InputMonoCompressed Italic Complete'
./gen.sh 'InputMonoCompressed Italic'
./gen.sh 'InputMonoCompressed Italic Complete'
./gen.sh 'InputMonoCompressed Italic'
./gen.sh 'InputMonoCompressed'
./gen.sh 'InputMonoCompressed Light Complete Mono'
./gen.sh 'InputMonoCompressed Light Complete'
./gen.sh 'InputMonoCompressed Light'
./gen.sh 'InputMonoCompressed Light Complete'
./gen.sh 'InputMonoCompressed Light'
./gen.sh 'InputMonoCompressed'
./gen.sh 'InputMonoCompressed LightIta Complete Mono'
./gen.sh 'InputMonoCompressed LightIta Complete'
./gen.sh 'InputMonoCompressed LightIta'
./gen.sh 'InputMonoCompressed LightIta Complete'
./gen.sh 'InputMonoCompressed LightIta'
./gen.sh 'InputMonoCompressed'
./gen.sh 'InputMonoCompressed Medium Complete Mono'
./gen.sh 'InputMonoCompressed Medium Complete'
./gen.sh 'InputMonoCompressed Medium'
./gen.sh 'InputMonoCompressed Medium Complete'
./gen.sh 'InputMonoCompressed Medium'
./gen.sh 'InputMonoCompressed'
./gen.sh 'InputMonoCompressed MediumIta Complete Mono'
./gen.sh 'InputMonoCompressed MediumIta Complete'
./gen.sh 'InputMonoCompressed MediumIta'
./gen.sh 'InputMonoCompressed MediumIta Complete'
./gen.sh 'InputMonoCompressed MediumIta'
./gen.sh 'InputMonoCompressed'
./gen.sh 'InputMonoCompressed Thin Complete Mono'
./gen.sh 'InputMonoCompressed Thin Complete'
./gen.sh 'InputMonoCompressed Thin'
./gen.sh 'InputMonoCompressed Thin Complete'
./gen.sh 'InputMonoCompressed Thin'
./gen.sh 'InputMonoCompressed'
./gen.sh 'InputMonoCompressed ThinIta Complete Mono'
./gen.sh 'InputMonoCompressed ThinIta Complete'
./gen.sh 'InputMonoCompressed ThinIta'
./gen.sh 'InputMonoCompressed ThinIta Complete'
./gen.sh 'InputMonoCompressed ThinIta'
./gen.sh 'InputMonoCompressed'
./gen.sh 'InputMonoCondensed Black Complete Mono'
./gen.sh 'InputMonoCondensed Black Complete'
./gen.sh 'InputMonoCondensed Black'
./gen.sh 'InputMonoCondensed Black Complete'
./gen.sh 'InputMonoCondensed Black'
./gen.sh 'InputMonoCondensed'
./gen.sh 'InputMonoCondensed BlackIta Complete Mono'
./gen.sh 'InputMonoCondensed BlackIta Complete'
./gen.sh 'InputMonoCondensed BlackIta'
./gen.sh 'InputMonoCondensed BlackIta Complete'
./gen.sh 'InputMonoCondensed BlackIta'
./gen.sh 'InputMonoCondensed'
./gen.sh 'InputMonoCondensed Bold Complete Mono'
./gen.sh 'InputMonoCondensed Bold Complete'
./gen.sh 'InputMonoCondensed Bold'
./gen.sh 'InputMonoCondensed Bold Complete'
./gen.sh 'InputMonoCondensed Bold'
./gen.sh 'InputMonoCondensed'
./gen.sh 'InputMonoCondensed BoldIta Complete Mono'
./gen.sh 'InputMonoCondensed BoldIta Complete'
./gen.sh 'InputMonoCondensed BoldIta'
./gen.sh 'InputMonoCondensed BoldIta Complete'
./gen.sh 'InputMonoCondensed BoldIta'
./gen.sh 'InputMonoCondensed'
./gen.sh 'InputMonoCondensed Complete Mono'
./gen.sh 'InputMonoCondensed Complete'
./gen.sh 'InputMonoCondensed'
./gen.sh 'InputMonoCondensed Complete'
./gen.sh 'InputMonoCondensed'
./gen.sh 'InputMonoCondensed'
./gen.sh 'InputMonoCondensed ExLight Complete Mono'
./gen.sh 'InputMonoCondensed ExLight Complete'
./gen.sh 'InputMonoCondensed ExLight'
./gen.sh 'InputMonoCondensed ExLight Complete'
./gen.sh 'InputMonoCondensed ExLight'
./gen.sh 'InputMonoCondensed'
./gen.sh 'InputMonoCondensed ExLightIta Complete Mono'
./gen.sh 'InputMonoCondensed ExLightIta Complete'
./gen.sh 'InputMonoCondensed ExLightIta'
./gen.sh 'InputMonoCondensed ExLightIta Complete'
./gen.sh 'InputMonoCondensed ExLightIta'
./gen.sh 'InputMonoCondensed'
./gen.sh 'InputMonoCondensed Italic Complete Mono'
./gen.sh 'InputMonoCondensed Italic Complete'
./gen.sh 'InputMonoCondensed Italic'
./gen.sh 'InputMonoCondensed Italic Complete'
./gen.sh 'InputMonoCondensed Italic'
./gen.sh 'InputMonoCondensed'
./gen.sh 'InputMonoCondensed Light Complete Mono'
./gen.sh 'InputMonoCondensed Light Complete'
./gen.sh 'InputMonoCondensed Light'
./gen.sh 'InputMonoCondensed Light Complete'
./gen.sh 'InputMonoCondensed Light'
./gen.sh 'InputMonoCondensed'
./gen.sh 'InputMonoCondensed LightIta Complete Mono'
./gen.sh 'InputMonoCondensed LightIta Complete'
./gen.sh 'InputMonoCondensed LightIta'
./gen.sh 'InputMonoCondensed LightIta Complete'
./gen.sh 'InputMonoCondensed LightIta'
./gen.sh 'InputMonoCondensed'
./gen.sh 'InputMonoCondensed Medium Complete Mono'
./gen.sh 'InputMonoCondensed Medium Complete'
./gen.sh 'InputMonoCondensed Medium'
./gen.sh 'InputMonoCondensed Medium Complete'
./gen.sh 'InputMonoCondensed Medium'
./gen.sh 'InputMonoCondensed'
./gen.sh 'InputMonoCondensed MediumIta Complete Mono'
./gen.sh 'InputMonoCondensed MediumIta Complete'
./gen.sh 'InputMonoCondensed MediumIta'
./gen.sh 'InputMonoCondensed MediumIta Complete'
./gen.sh 'InputMonoCondensed MediumIta'
./gen.sh 'InputMonoCondensed'
./gen.sh 'InputMonoCondensed Thin Complete Mono'
./gen.sh 'InputMonoCondensed Thin Complete'
./gen.sh 'InputMonoCondensed Thin'
./gen.sh 'InputMonoCondensed Thin Complete'
./gen.sh 'InputMonoCondensed Thin'
./gen.sh 'InputMonoCondensed'
./gen.sh 'InputMonoCondensed ThinIta Complete Mono'
./gen.sh 'InputMonoCondensed ThinIta Complete'
./gen.sh 'InputMonoCondensed ThinIta'
./gen.sh 'InputMonoCondensed ThinIta Complete'
./gen.sh 'InputMonoCondensed ThinIta'
./gen.sh 'InputMonoCondensed'
./gen.sh 'InputMonoNarrow Black Complete Mono'
./gen.sh 'InputMonoNarrow Black Complete'
./gen.sh 'InputMonoNarrow Black'
./gen.sh 'InputMonoNarrow Black Complete'
./gen.sh 'InputMonoNarrow Black'
./gen.sh 'InputMonoNarrow'
./gen.sh 'InputMonoNarrow BlackIta Complete Mono'
./gen.sh 'InputMonoNarrow BlackIta Complete'
./gen.sh 'InputMonoNarrow BlackIta'
./gen.sh 'InputMonoNarrow BlackIta Complete'
./gen.sh 'InputMonoNarrow BlackIta'
./gen.sh 'InputMonoNarrow'
./gen.sh 'InputMonoNarrow Bold Complete Mono'
./gen.sh 'InputMonoNarrow Bold Complete'
./gen.sh 'InputMonoNarrow Bold'
./gen.sh 'InputMonoNarrow Bold Complete'
./gen.sh 'InputMonoNarrow Bold'
./gen.sh 'InputMonoNarrow'
./gen.sh 'InputMonoNarrow BoldIta Complete Mono'
./gen.sh 'InputMonoNarrow BoldIta Complete'
./gen.sh 'InputMonoNarrow BoldIta'
./gen.sh 'InputMonoNarrow BoldIta Complete'
./gen.sh 'InputMonoNarrow BoldIta'
./gen.sh 'InputMonoNarrow'
./gen.sh 'InputMonoNarrow Complete Mono'
./gen.sh 'InputMonoNarrow Complete'
./gen.sh 'InputMonoNarrow'
./gen.sh 'InputMonoNarrow Complete'
./gen.sh 'InputMonoNarrow'
./gen.sh 'InputMonoNarrow'
./gen.sh 'InputMonoNarrow ExLight Complete Mono'
./gen.sh 'InputMonoNarrow ExLight Complete'
./gen.sh 'InputMonoNarrow ExLight'
./gen.sh 'InputMonoNarrow ExLight Complete'
./gen.sh 'InputMonoNarrow ExLight'
./gen.sh 'InputMonoNarrow'
./gen.sh 'InputMonoNarrow ExLightIta Complete Mono'
./gen.sh 'InputMonoNarrow ExLightIta Complete'
./gen.sh 'InputMonoNarrow ExLightIta'
./gen.sh 'InputMonoNarrow ExLightIta Complete'
./gen.sh 'InputMonoNarrow ExLightIta'
./gen.sh 'InputMonoNarrow'
./gen.sh 'InputMonoNarrow Italic Complete Mono'
./gen.sh 'InputMonoNarrow Italic Complete'
./gen.sh 'InputMonoNarrow Italic'
./gen.sh 'InputMonoNarrow Italic Complete'
./gen.sh 'InputMonoNarrow Italic'
./gen.sh 'InputMonoNarrow'
./gen.sh 'InputMonoNarrow Light Complete Mono'
./gen.sh 'InputMonoNarrow Light Complete'
./gen.sh 'InputMonoNarrow Light'
./gen.sh 'InputMonoNarrow Light Complete'
./gen.sh 'InputMonoNarrow Light'
./gen.sh 'InputMonoNarrow'
./gen.sh 'InputMonoNarrow LightIta Complete Mono'
./gen.sh 'InputMonoNarrow LightIta Complete'
./gen.sh 'InputMonoNarrow LightIta'
./gen.sh 'InputMonoNarrow LightIta Complete'
./gen.sh 'InputMonoNarrow LightIta'
./gen.sh 'InputMonoNarrow'
./gen.sh 'InputMonoNarrow Medium Complete Mono'
./gen.sh 'InputMonoNarrow Medium Complete'
./gen.sh 'InputMonoNarrow Medium'
./gen.sh 'InputMonoNarrow Medium Complete'
./gen.sh 'InputMonoNarrow Medium'
./gen.sh 'InputMonoNarrow'
./gen.sh 'InputMonoNarrow MediumIta Complete Mono'
./gen.sh 'InputMonoNarrow MediumIta Complete'
./gen.sh 'InputMonoNarrow MediumIta'
./gen.sh 'InputMonoNarrow MediumIta Complete'
./gen.sh 'InputMonoNarrow MediumIta'
./gen.sh 'InputMonoNarrow'
./gen.sh 'InputMonoNarrow Thin Complete Mono'
./gen.sh 'InputMonoNarrow Thin Complete'
./gen.sh 'InputMonoNarrow Thin'
./gen.sh 'InputMonoNarrow Thin Complete'
./gen.sh 'InputMonoNarrow Thin'
./gen.sh 'InputMonoNarrow'
./gen.sh 'InputMonoNarrow ThinIta Complete Mono'
./gen.sh 'InputMonoNarrow ThinIta Complete'
./gen.sh 'InputMonoNarrow ThinIta'
./gen.sh 'InputMonoNarrow ThinIta Complete'
./gen.sh 'InputMonoNarrow ThinIta'
./gen.sh 'InputMonoNarrow'
./gen.sh 'InputSans Black Complete Mono'
./gen.sh 'InputSans Black Complete'
./gen.sh 'InputSans Black'
./gen.sh 'InputSans Black Complete'
./gen.sh 'InputSans Black'
./gen.sh 'InputSans'
./gen.sh 'InputSans BlackIta Complete Mono'
./gen.sh 'InputSans BlackIta Complete'
./gen.sh 'InputSans BlackIta'
./gen.sh 'InputSans BlackIta Complete'
./gen.sh 'InputSans BlackIta'
./gen.sh 'InputSans'
./gen.sh 'InputSans Bold Complete Mono'
./gen.sh 'InputSans Bold Complete'
./gen.sh 'InputSans Bold'
./gen.sh 'InputSans Bold Complete'
./gen.sh 'InputSans Bold'
./gen.sh 'InputSans'
./gen.sh 'InputSans BoldIta Complete Mono'
./gen.sh 'InputSans BoldIta Complete'
./gen.sh 'InputSans BoldIta'
./gen.sh 'InputSans BoldIta Complete'
./gen.sh 'InputSans BoldIta'
./gen.sh 'InputSans'
./gen.sh 'InputSans Complete Mono'
./gen.sh 'InputSans Complete'
./gen.sh 'InputSans'
./gen.sh 'InputSans Complete'
./gen.sh 'InputSans'
./gen.sh 'InputSans'
./gen.sh 'InputSans ExLight Complete Mono'
./gen.sh 'InputSans ExLight Complete'
./gen.sh 'InputSans ExLight'
./gen.sh 'InputSans ExLight Complete'
./gen.sh 'InputSans ExLight'
./gen.sh 'InputSans'
./gen.sh 'InputSans ExLightIta Complete Mono'
./gen.sh 'InputSans ExLightIta Complete'
./gen.sh 'InputSans ExLightIta'
./gen.sh 'InputSans ExLightIta Complete'
./gen.sh 'InputSans ExLightIta'
./gen.sh 'InputSans'
./gen.sh 'InputSans Italic Complete Mono'
./gen.sh 'InputSans Italic Complete'
./gen.sh 'InputSans Italic'
./gen.sh 'InputSans Italic Complete'
./gen.sh 'InputSans Italic'
./gen.sh 'InputSans'
./gen.sh 'InputSans Light Complete Mono'
./gen.sh 'InputSans Light Complete'
./gen.sh 'InputSans Light'
./gen.sh 'InputSans Light Complete'
./gen.sh 'InputSans Light'
./gen.sh 'InputSans'
./gen.sh 'InputSans LightIta Complete Mono'
./gen.sh 'InputSans LightIta Complete'
./gen.sh 'InputSans LightIta'
./gen.sh 'InputSans LightIta Complete'
./gen.sh 'InputSans LightIta'
./gen.sh 'InputSans'
./gen.sh 'InputSans Medium Complete Mono'
./gen.sh 'InputSans Medium Complete'
./gen.sh 'InputSans Medium'
./gen.sh 'InputSans Medium Complete'
./gen.sh 'InputSans Medium'
./gen.sh 'InputSans'
./gen.sh 'InputSans MediumIta Complete Mono'
./gen.sh 'InputSans MediumIta Complete'
./gen.sh 'InputSans MediumIta'
./gen.sh 'InputSans MediumIta Complete'
./gen.sh 'InputSans MediumIta'
./gen.sh 'InputSans'
./gen.sh 'InputSans Thin Complete Mono'
./gen.sh 'InputSans Thin Complete'
./gen.sh 'InputSans Thin'
./gen.sh 'InputSans Thin Complete'
./gen.sh 'InputSans Thin'
./gen.sh 'InputSans'
./gen.sh 'InputSans ThinIta Complete Mono'
./gen.sh 'InputSans ThinIta Complete'
./gen.sh 'InputSans ThinIta'
./gen.sh 'InputSans ThinIta Complete'
./gen.sh 'InputSans ThinIta'
./gen.sh 'InputSans'
./gen.sh 'InputSansCompressed Black Complete Mono'
./gen.sh 'InputSansCompressed Black Complete'
./gen.sh 'InputSansCompressed Black'
./gen.sh 'InputSansCompressed Black Complete'
./gen.sh 'InputSansCompressed Black'
./gen.sh 'InputSansCompressed'
./gen.sh 'InputSansCompressed BlackIta Complete Mono'
./gen.sh 'InputSansCompressed BlackIta Complete'
./gen.sh 'InputSansCompressed BlackIta'
./gen.sh 'InputSansCompressed BlackIta Complete'
./gen.sh 'InputSansCompressed BlackIta'
./gen.sh 'InputSansCompressed'
./gen.sh 'InputSansCompressed Bold Complete Mono'
./gen.sh 'InputSansCompressed Bold Complete'
./gen.sh 'InputSansCompressed Bold'
./gen.sh 'InputSansCompressed Bold Complete'
./gen.sh 'InputSansCompressed Bold'
./gen.sh 'InputSansCompressed'
./gen.sh 'InputSansCompressed BoldIta Complete Mono'
./gen.sh 'InputSansCompressed BoldIta Complete'
./gen.sh 'InputSansCompressed BoldIta'
./gen.sh 'InputSansCompressed BoldIta Complete'
./gen.sh 'InputSansCompressed BoldIta'
./gen.sh 'InputSansCompressed'
./gen.sh 'InputSansCompressed Complete Mono'
./gen.sh 'InputSansCompressed Complete'
./gen.sh 'InputSansCompressed'
./gen.sh 'InputSansCompressed Complete'
./gen.sh 'InputSansCompressed'
./gen.sh 'InputSansCompressed'
./gen.sh 'InputSansCompressed ExLight Complete Mono'
./gen.sh 'InputSansCompressed ExLight Complete'
./gen.sh 'InputSansCompressed ExLight'
./gen.sh 'InputSansCompressed ExLight Complete'
./gen.sh 'InputSansCompressed ExLight'
./gen.sh 'InputSansCompressed'
./gen.sh 'InputSansCompressed ExLightIta Complete Mono'
./gen.sh 'InputSansCompressed ExLightIta Complete'
./gen.sh 'InputSansCompressed ExLightIta'
./gen.sh 'InputSansCompressed ExLightIta Complete'
./gen.sh 'InputSansCompressed ExLightIta'
./gen.sh 'InputSansCompressed'
./gen.sh 'InputSansCompressed Italic Complete Mono'
./gen.sh 'InputSansCompressed Italic Complete'
./gen.sh 'InputSansCompressed Italic'
./gen.sh 'InputSansCompressed Italic Complete'
./gen.sh 'InputSansCompressed Italic'
./gen.sh 'InputSansCompressed'
./gen.sh 'InputSansCompressed Light Complete Mono'
./gen.sh 'InputSansCompressed Light Complete'
./gen.sh 'InputSansCompressed Light'
./gen.sh 'InputSansCompressed Light Complete'
./gen.sh 'InputSansCompressed Light'
./gen.sh 'InputSansCompressed'
./gen.sh 'InputSansCompressed LightIta Complete Mono'
./gen.sh 'InputSansCompressed LightIta Complete'
./gen.sh 'InputSansCompressed LightIta'
./gen.sh 'InputSansCompressed LightIta Complete'
./gen.sh 'InputSansCompressed LightIta'
./gen.sh 'InputSansCompressed'
./gen.sh 'InputSansCompressed Medium Complete Mono'
./gen.sh 'InputSansCompressed Medium Complete'
./gen.sh 'InputSansCompressed Medium'
./gen.sh 'InputSansCompressed Medium Complete'
./gen.sh 'InputSansCompressed Medium'
./gen.sh 'InputSansCompressed'
./gen.sh 'InputSansCompressed MediumIta Complete Mono'
./gen.sh 'InputSansCompressed MediumIta Complete'
./gen.sh 'InputSansCompressed MediumIta'
./gen.sh 'InputSansCompressed MediumIta Complete'
./gen.sh 'InputSansCompressed MediumIta'
./gen.sh 'InputSansCompressed'
./gen.sh 'InputSansCompressed Thin Complete Mono'
./gen.sh 'InputSansCompressed Thin Complete'
./gen.sh 'InputSansCompressed Thin'
./gen.sh 'InputSansCompressed Thin Complete'
./gen.sh 'InputSansCompressed Thin'
./gen.sh 'InputSansCompressed'
./gen.sh 'InputSansCompressed ThinIta Complete Mono'
./gen.sh 'InputSansCompressed ThinIta Complete'
./gen.sh 'InputSansCompressed ThinIta'
./gen.sh 'InputSansCompressed ThinIta Complete'
./gen.sh 'InputSansCompressed ThinIta'
./gen.sh 'InputSansCompressed'
./gen.sh 'InputSansCondensed Black Complete Mono'
./gen.sh 'InputSansCondensed Black Complete'
./gen.sh 'InputSansCondensed Black'
./gen.sh 'InputSansCondensed Black Complete'
./gen.sh 'InputSansCondensed Black'
./gen.sh 'InputSansCondensed'
./gen.sh 'InputSansCondensed BlackIta Complete Mono'
./gen.sh 'InputSansCondensed BlackIta Complete'
./gen.sh 'InputSansCondensed BlackIta'
./gen.sh 'InputSansCondensed BlackIta Complete'
./gen.sh 'InputSansCondensed BlackIta'
./gen.sh 'InputSansCondensed'
./gen.sh 'InputSansCondensed Bold Complete Mono'
./gen.sh 'InputSansCondensed Bold Complete'
./gen.sh 'InputSansCondensed Bold'
./gen.sh 'InputSansCondensed Bold Complete'
./gen.sh 'InputSansCondensed Bold'
./gen.sh 'InputSansCondensed'
./gen.sh 'InputSansCondensed BoldIta Complete Mono'
./gen.sh 'InputSansCondensed BoldIta Complete'
./gen.sh 'InputSansCondensed BoldIta'
./gen.sh 'InputSansCondensed BoldIta Complete'
./gen.sh 'InputSansCondensed BoldIta'
./gen.sh 'InputSansCondensed'
./gen.sh 'InputSansCondensed Complete Mono'
./gen.sh 'InputSansCondensed Complete'
./gen.sh 'InputSansCondensed'
./gen.sh 'InputSansCondensed Complete'
./gen.sh 'InputSansCondensed'
./gen.sh 'InputSansCondensed'
./gen.sh 'InputSansCondensed ExLight Complete Mono'
./gen.sh 'InputSansCondensed ExLight Complete'
./gen.sh 'InputSansCondensed ExLight'
./gen.sh 'InputSansCondensed ExLight Complete'
./gen.sh 'InputSansCondensed ExLight'
./gen.sh 'InputSansCondensed'
./gen.sh 'InputSansCondensed ExLightIta Complete Mono'
./gen.sh 'InputSansCondensed ExLightIta Complete'
./gen.sh 'InputSansCondensed ExLightIta'
./gen.sh 'InputSansCondensed ExLightIta Complete'
./gen.sh 'InputSansCondensed ExLightIta'
./gen.sh 'InputSansCondensed'
./gen.sh 'InputSansCondensed Italic Complete Mono'
./gen.sh 'InputSansCondensed Italic Complete'
./gen.sh 'InputSansCondensed Italic'
./gen.sh 'InputSansCondensed Italic Complete'
./gen.sh 'InputSansCondensed Italic'
./gen.sh 'InputSansCondensed'
./gen.sh 'InputSansCondensed Light Complete Mono'
./gen.sh 'InputSansCondensed Light Complete'
./gen.sh 'InputSansCondensed Light'
./gen.sh 'InputSansCondensed Light Complete'
./gen.sh 'InputSansCondensed Light'
./gen.sh 'InputSansCondensed'
./gen.sh 'InputSansCondensed LightIta Complete Mono'
./gen.sh 'InputSansCondensed LightIta Complete'
./gen.sh 'InputSansCondensed LightIta'
./gen.sh 'InputSansCondensed LightIta Complete'
./gen.sh 'InputSansCondensed LightIta'
./gen.sh 'InputSansCondensed'
./gen.sh 'InputSansCondensed Medium Complete Mono'
./gen.sh 'InputSansCondensed Medium Complete'
./gen.sh 'InputSansCondensed Medium'
./gen.sh 'InputSansCondensed Medium Complete'
./gen.sh 'InputSansCondensed Medium'
./gen.sh 'InputSansCondensed'
./gen.sh 'InputSansCondensed MediumIta Complete Mono'
./gen.sh 'InputSansCondensed MediumIta Complete'
./gen.sh 'InputSansCondensed MediumIta'
./gen.sh 'InputSansCondensed MediumIta Complete'
./gen.sh 'InputSansCondensed MediumIta'
./gen.sh 'InputSansCondensed'
./gen.sh 'InputSansCondensed Thin Complete Mono'
./gen.sh 'InputSansCondensed Thin Complete'
./gen.sh 'InputSansCondensed Thin'
./gen.sh 'InputSansCondensed Thin Complete'
./gen.sh 'InputSansCondensed Thin'
./gen.sh 'InputSansCondensed'
./gen.sh 'InputSansCondensed ThinIta Complete Mono'
./gen.sh 'InputSansCondensed ThinIta Complete'
./gen.sh 'InputSansCondensed ThinIta'
./gen.sh 'InputSansCondensed ThinIta Complete'
./gen.sh 'InputSansCondensed ThinIta'
./gen.sh 'InputSansCondensed'
./gen.sh 'InputSansNarrow Black Complete Mono'
./gen.sh 'InputSansNarrow Black Complete'
./gen.sh 'InputSansNarrow Black'
./gen.sh 'InputSansNarrow Black Complete'
./gen.sh 'InputSansNarrow Black'
./gen.sh 'InputSansNarrow'
./gen.sh 'InputSansNarrow BlackIta Complete Mono'
./gen.sh 'InputSansNarrow BlackIta Complete'
./gen.sh 'InputSansNarrow BlackIta'
./gen.sh 'InputSansNarrow BlackIta Complete'
./gen.sh 'InputSansNarrow BlackIta'
./gen.sh 'InputSansNarrow'
./gen.sh 'InputSansNarrow Bold Complete Mono'
./gen.sh 'InputSansNarrow Bold Complete'
./gen.sh 'InputSansNarrow Bold'
./gen.sh 'InputSansNarrow Bold Complete'
./gen.sh 'InputSansNarrow Bold'
./gen.sh 'InputSansNarrow'
./gen.sh 'InputSansNarrow BoldIta Complete Mono'
./gen.sh 'InputSansNarrow BoldIta Complete'
./gen.sh 'InputSansNarrow BoldIta'
./gen.sh 'InputSansNarrow BoldIta Complete'
./gen.sh 'InputSansNarrow BoldIta'
./gen.sh 'InputSansNarrow'
./gen.sh 'InputSansNarrow Complete Mono'
./gen.sh 'InputSansNarrow Complete'
./gen.sh 'InputSansNarrow'
./gen.sh 'InputSansNarrow Complete'
./gen.sh 'InputSansNarrow'
./gen.sh 'InputSansNarrow'
./gen.sh 'InputSansNarrow ExLight Complete Mono'
./gen.sh 'InputSansNarrow ExLight Complete'
./gen.sh 'InputSansNarrow ExLight'
./gen.sh 'InputSansNarrow ExLight Complete'
./gen.sh 'InputSansNarrow ExLight'
./gen.sh 'InputSansNarrow'
./gen.sh 'InputSansNarrow ExLightIta Complete Mono'
./gen.sh 'InputSansNarrow ExLightIta Complete'
./gen.sh 'InputSansNarrow ExLightIta'
./gen.sh 'InputSansNarrow ExLightIta Complete'
./gen.sh 'InputSansNarrow ExLightIta'
./gen.sh 'InputSansNarrow'
./gen.sh 'InputSansNarrow Italic Complete Mono'
./gen.sh 'InputSansNarrow Italic Complete'
./gen.sh 'InputSansNarrow Italic'
./gen.sh 'InputSansNarrow Italic Complete'
./gen.sh 'InputSansNarrow Italic'
./gen.sh 'InputSansNarrow'
./gen.sh 'InputSansNarrow Light Complete Mono'
./gen.sh 'InputSansNarrow Light Complete'
./gen.sh 'InputSansNarrow Light'
./gen.sh 'InputSansNarrow Light Complete'
./gen.sh 'InputSansNarrow Light'
./gen.sh 'InputSansNarrow'
./gen.sh 'InputSansNarrow LightIta Complete Mono'
./gen.sh 'InputSansNarrow LightIta Complete'
./gen.sh 'InputSansNarrow LightIta'
./gen.sh 'InputSansNarrow LightIta Complete'
./gen.sh 'InputSansNarrow LightIta'
./gen.sh 'InputSansNarrow'
./gen.sh 'InputSansNarrow Medium Complete Mono'
./gen.sh 'InputSansNarrow Medium Complete'
./gen.sh 'InputSansNarrow Medium'
./gen.sh 'InputSansNarrow Medium Complete'
./gen.sh 'InputSansNarrow Medium'
./gen.sh 'InputSansNarrow'
./gen.sh 'InputSansNarrow MediumIta Complete Mono'
./gen.sh 'InputSansNarrow MediumIta Complete'
./gen.sh 'InputSansNarrow MediumIta'
./gen.sh 'InputSansNarrow MediumIta Complete'
./gen.sh 'InputSansNarrow MediumIta'
./gen.sh 'InputSansNarrow'
./gen.sh 'InputSansNarrow Thin Complete Mono'
./gen.sh 'InputSansNarrow Thin Complete'
./gen.sh 'InputSansNarrow Thin'
./gen.sh 'InputSansNarrow Thin Complete'
./gen.sh 'InputSansNarrow Thin'
./gen.sh 'InputSansNarrow'
./gen.sh 'InputSansNarrow ThinIta Complete Mono'
./gen.sh 'InputSansNarrow ThinIta Complete'
./gen.sh 'InputSansNarrow ThinIta'
./gen.sh 'InputSansNarrow ThinIta Complete'
./gen.sh 'InputSansNarrow ThinIta'
./gen.sh 'InputSansNarrow'
./gen.sh 'InputSerif Black Complete Mono'
./gen.sh 'InputSerif Black Complete'
./gen.sh 'InputSerif Black'
./gen.sh 'InputSerif Black Complete'
./gen.sh 'InputSerif Black'
./gen.sh 'InputSerif'
./gen.sh 'InputSerif BlackIta Complete Mono'
./gen.sh 'InputSerif BlackIta Complete'
./gen.sh 'InputSerif BlackIta'
./gen.sh 'InputSerif BlackIta Complete'
./gen.sh 'InputSerif BlackIta'
./gen.sh 'InputSerif'
./gen.sh 'InputSerif Bold Complete Mono'
./gen.sh 'InputSerif Bold Complete'
./gen.sh 'InputSerif Bold'
./gen.sh 'InputSerif Bold Complete'
./gen.sh 'InputSerif Bold'
./gen.sh 'InputSerif'
./gen.sh 'InputSerif BoldIta Complete Mono'
./gen.sh 'InputSerif BoldIta Complete'
./gen.sh 'InputSerif BoldIta'
./gen.sh 'InputSerif BoldIta Complete'
./gen.sh 'InputSerif BoldIta'
./gen.sh 'InputSerif'
./gen.sh 'InputSerif Complete Mono'
./gen.sh 'InputSerif Complete'
./gen.sh 'InputSerif'
./gen.sh 'InputSerif Complete'
./gen.sh 'InputSerif'
./gen.sh 'InputSerif'
./gen.sh 'InputSerif ExLight Complete Mono'
./gen.sh 'InputSerif ExLight Complete'
./gen.sh 'InputSerif ExLight'
./gen.sh 'InputSerif ExLight Complete'
./gen.sh 'InputSerif ExLight'
./gen.sh 'InputSerif'
./gen.sh 'InputSerif ExLightIta Complete Mono'
./gen.sh 'InputSerif ExLightIta Complete'
./gen.sh 'InputSerif ExLightIta'
./gen.sh 'InputSerif ExLightIta Complete'
./gen.sh 'InputSerif ExLightIta'
./gen.sh 'InputSerif'
./gen.sh 'InputSerif Italic Complete Mono'
./gen.sh 'InputSerif Italic Complete'
./gen.sh 'InputSerif Italic'
./gen.sh 'InputSerif Italic Complete'
./gen.sh 'InputSerif Italic'
./gen.sh 'InputSerif'
./gen.sh 'InputSerif Light Complete Mono'
./gen.sh 'InputSerif Light Complete'
./gen.sh 'InputSerif Light'
./gen.sh 'InputSerif Light Complete'
./gen.sh 'InputSerif Light'
./gen.sh 'InputSerif'
./gen.sh 'InputSerif LightIta Complete Mono'
./gen.sh 'InputSerif LightIta Complete'
./gen.sh 'InputSerif LightIta'
./gen.sh 'InputSerif LightIta Complete'
./gen.sh 'InputSerif LightIta'
./gen.sh 'InputSerif'
./gen.sh 'InputSerif Medium Complete Mono'
./gen.sh 'InputSerif Medium Complete'
./gen.sh 'InputSerif Medium'
./gen.sh 'InputSerif Medium Complete'
./gen.sh 'InputSerif Medium'
./gen.sh 'InputSerif'
./gen.sh 'InputSerif MediumIta Complete Mono'
./gen.sh 'InputSerif MediumIta Complete'
./gen.sh 'InputSerif MediumIta'
./gen.sh 'InputSerif MediumIta Complete'
./gen.sh 'InputSerif MediumIta'
./gen.sh 'InputSerif'
./gen.sh 'InputSerif Thin Complete Mono'
./gen.sh 'InputSerif Thin Complete'
./gen.sh 'InputSerif Thin'
./gen.sh 'InputSerif Thin Complete'
./gen.sh 'InputSerif Thin'
./gen.sh 'InputSerif'
./gen.sh 'InputSerif ThinIta Complete Mono'
./gen.sh 'InputSerif ThinIta Complete'
./gen.sh 'InputSerif ThinIta'
./gen.sh 'InputSerif ThinIta Complete'
./gen.sh 'InputSerif ThinIta'
./gen.sh 'InputSerif'
./gen.sh 'InputSerifCompressed Black Complete Mono'
./gen.sh 'InputSerifCompressed Black Complete'
./gen.sh 'InputSerifCompressed Black'
./gen.sh 'InputSerifCompressed Black Complete'
./gen.sh 'InputSerifCompressed Black'
./gen.sh 'InputSerifCompressed'
./gen.sh 'InputSerifCompressed BlackIta Complete Mono'
./gen.sh 'InputSerifCompressed BlackIta Complete'
./gen.sh 'InputSerifCompressed BlackIta'
./gen.sh 'InputSerifCompressed BlackIta Complete'
./gen.sh 'InputSerifCompressed BlackIta'
./gen.sh 'InputSerifCompressed'
./gen.sh 'InputSerifCompressed Bold Complete Mono'
./gen.sh 'InputSerifCompressed Bold Complete'
./gen.sh 'InputSerifCompressed Bold'
./gen.sh 'InputSerifCompressed Bold Complete'
./gen.sh 'InputSerifCompressed Bold'
./gen.sh 'InputSerifCompressed'
./gen.sh 'InputSerifCompressed BoldIta Complete Mono'
./gen.sh 'InputSerifCompressed BoldIta Complete'
./gen.sh 'InputSerifCompressed BoldIta'
./gen.sh 'InputSerifCompressed BoldIta Complete'
./gen.sh 'InputSerifCompressed BoldIta'
./gen.sh 'InputSerifCompressed'
./gen.sh 'InputSerifCompressed Complete Mono'
./gen.sh 'InputSerifCompressed Complete'
./gen.sh 'InputSerifCompressed'
./gen.sh 'InputSerifCompressed Complete'
./gen.sh 'InputSerifCompressed'
./gen.sh 'InputSerifCompressed'
./gen.sh 'InputSerifCompressed ExLight Complete Mono'
./gen.sh 'InputSerifCompressed ExLight Complete'
./gen.sh 'InputSerifCompressed ExLight'
./gen.sh 'InputSerifCompressed ExLight Complete'
./gen.sh 'InputSerifCompressed ExLight'
./gen.sh 'InputSerifCompressed'
./gen.sh 'InputSerifCompressed ExLightIta Complete Mono'
./gen.sh 'InputSerifCompressed ExLightIta Complete'
./gen.sh 'InputSerifCompressed ExLightIta'
./gen.sh 'InputSerifCompressed ExLightIta Complete'
./gen.sh 'InputSerifCompressed ExLightIta'
./gen.sh 'InputSerifCompressed'
./gen.sh 'InputSerifCompressed Italic Complete Mono'
./gen.sh 'InputSerifCompressed Italic Complete'
./gen.sh 'InputSerifCompressed Italic'
./gen.sh 'InputSerifCompressed Italic Complete'
./gen.sh 'InputSerifCompressed Italic'
./gen.sh 'InputSerifCompressed'
./gen.sh 'InputSerifCompressed Light Complete Mono'
./gen.sh 'InputSerifCompressed Light Complete'
./gen.sh 'InputSerifCompressed Light'
./gen.sh 'InputSerifCompressed Light Complete'
./gen.sh 'InputSerifCompressed Light'
./gen.sh 'InputSerifCompressed'
./gen.sh 'InputSerifCompressed LightIta Complete Mono'
./gen.sh 'InputSerifCompressed LightIta Complete'
./gen.sh 'InputSerifCompressed LightIta'
./gen.sh 'InputSerifCompressed LightIta Complete'
./gen.sh 'InputSerifCompressed LightIta'
./gen.sh 'InputSerifCompressed'
./gen.sh 'InputSerifCompressed Medium Complete Mono'
./gen.sh 'InputSerifCompressed Medium Complete'
./gen.sh 'InputSerifCompressed Medium'
./gen.sh 'InputSerifCompressed Medium Complete'
./gen.sh 'InputSerifCompressed Medium'
./gen.sh 'InputSerifCompressed'
./gen.sh 'InputSerifCompressed MediumIta Complete Mono'
./gen.sh 'InputSerifCompressed MediumIta Complete'
./gen.sh 'InputSerifCompressed MediumIta'
./gen.sh 'InputSerifCompressed MediumIta Complete'
./gen.sh 'InputSerifCompressed MediumIta'
./gen.sh 'InputSerifCompressed'
./gen.sh 'InputSerifCompressed Thin Complete Mono'
./gen.sh 'InputSerifCompressed Thin Complete'
./gen.sh 'InputSerifCompressed Thin'
./gen.sh 'InputSerifCompressed Thin Complete'
./gen.sh 'InputSerifCompressed Thin'
./gen.sh 'InputSerifCompressed'
./gen.sh 'InputSerifCompressed ThinIta Complete Mono'
./gen.sh 'InputSerifCompressed ThinIta Complete'
./gen.sh 'InputSerifCompressed ThinIta'
./gen.sh 'InputSerifCompressed ThinIta Complete'
./gen.sh 'InputSerifCompressed ThinIta'
./gen.sh 'InputSerifCompressed'
./gen.sh 'InputSerifCondensed Black Complete Mono'
./gen.sh 'InputSerifCondensed Black Complete'
./gen.sh 'InputSerifCondensed Black'
./gen.sh 'InputSerifCondensed Black Complete'
./gen.sh 'InputSerifCondensed Black'
./gen.sh 'InputSerifCondensed'
./gen.sh 'InputSerifCondensed BlackIta Complete Mono'
./gen.sh 'InputSerifCondensed BlackIta Complete'
./gen.sh 'InputSerifCondensed BlackIta'
./gen.sh 'InputSerifCondensed BlackIta Complete'
./gen.sh 'InputSerifCondensed BlackIta'
./gen.sh 'InputSerifCondensed'
./gen.sh 'InputSerifCondensed Bold Complete Mono'
./gen.sh 'InputSerifCondensed Bold Complete'
./gen.sh 'InputSerifCondensed Bold'
./gen.sh 'InputSerifCondensed Bold Complete'
./gen.sh 'InputSerifCondensed Bold'
./gen.sh 'InputSerifCondensed'
./gen.sh 'InputSerifCondensed BoldIta Complete Mono'
./gen.sh 'InputSerifCondensed BoldIta Complete'
./gen.sh 'InputSerifCondensed BoldIta'
./gen.sh 'InputSerifCondensed BoldIta Complete'
./gen.sh 'InputSerifCondensed BoldIta'
./gen.sh 'InputSerifCondensed'
./gen.sh 'InputSerifCondensed Complete Mono'
./gen.sh 'InputSerifCondensed Complete'
./gen.sh 'InputSerifCondensed'
./gen.sh 'InputSerifCondensed Complete'
./gen.sh 'InputSerifCondensed'
./gen.sh 'InputSerifCondensed'
./gen.sh 'InputSerifCondensed ExLight Complete Mono'
./gen.sh 'InputSerifCondensed ExLight Complete'
./gen.sh 'InputSerifCondensed ExLight'
./gen.sh 'InputSerifCondensed ExLight Complete'
./gen.sh 'InputSerifCondensed ExLight'
./gen.sh 'InputSerifCondensed'
./gen.sh 'InputSerifCondensed ExLightIta Complete Mono'
./gen.sh 'InputSerifCondensed ExLightIta Complete'
./gen.sh 'InputSerifCondensed ExLightIta'
./gen.sh 'InputSerifCondensed ExLightIta Complete'
./gen.sh 'InputSerifCondensed ExLightIta'
./gen.sh 'InputSerifCondensed'
./gen.sh 'InputSerifCondensed Italic Complete Mono'
./gen.sh 'InputSerifCondensed Italic Complete'
./gen.sh 'InputSerifCondensed Italic'
./gen.sh 'InputSerifCondensed Italic Complete'
./gen.sh 'InputSerifCondensed Italic'
./gen.sh 'InputSerifCondensed'
./gen.sh 'InputSerifCondensed Light Complete Mono'
./gen.sh 'InputSerifCondensed Light Complete'
./gen.sh 'InputSerifCondensed Light'
./gen.sh 'InputSerifCondensed Light Complete'
./gen.sh 'InputSerifCondensed Light'
./gen.sh 'InputSerifCondensed'
./gen.sh 'InputSerifCondensed LightIta Complete Mono'
./gen.sh 'InputSerifCondensed LightIta Complete'
./gen.sh 'InputSerifCondensed LightIta'
./gen.sh 'InputSerifCondensed LightIta Complete'
./gen.sh 'InputSerifCondensed LightIta'
./gen.sh 'InputSerifCondensed'
./gen.sh 'InputSerifCondensed Medium Complete Mono'
./gen.sh 'InputSerifCondensed Medium Complete'
./gen.sh 'InputSerifCondensed Medium'
./gen.sh 'InputSerifCondensed Medium Complete'
./gen.sh 'InputSerifCondensed Medium'
./gen.sh 'InputSerifCondensed'
./gen.sh 'InputSerifCondensed MediumIta Complete Mono'
./gen.sh 'InputSerifCondensed MediumIta Complete'
./gen.sh 'InputSerifCondensed MediumIta'
./gen.sh 'InputSerifCondensed MediumIta Complete'
./gen.sh 'InputSerifCondensed MediumIta'
./gen.sh 'InputSerifCondensed'
./gen.sh 'InputSerifCondensed Thin Complete Mono'
./gen.sh 'InputSerifCondensed Thin Complete'
./gen.sh 'InputSerifCondensed Thin'
./gen.sh 'InputSerifCondensed Thin Complete'
./gen.sh 'InputSerifCondensed Thin'
./gen.sh 'InputSerifCondensed'
./gen.sh 'InputSerifCondensed ThinIta Complete Mono'
./gen.sh 'InputSerifCondensed ThinIta Complete'
./gen.sh 'InputSerifCondensed ThinIta'
./gen.sh 'InputSerifCondensed ThinIta Complete'
./gen.sh 'InputSerifCondensed ThinIta'
./gen.sh 'InputSerifCondensed'
./gen.sh 'InputSerifNarrow Black Complete Mono'
./gen.sh 'InputSerifNarrow Black Complete'
./gen.sh 'InputSerifNarrow Black'
./gen.sh 'InputSerifNarrow Black Complete'
./gen.sh 'InputSerifNarrow Black'
./gen.sh 'InputSerifNarrow'
./gen.sh 'InputSerifNarrow BlackIta Complete Mono'
./gen.sh 'InputSerifNarrow BlackIta Complete'
./gen.sh 'InputSerifNarrow BlackIta'
./gen.sh 'InputSerifNarrow BlackIta Complete'
./gen.sh 'InputSerifNarrow BlackIta'
./gen.sh 'InputSerifNarrow'
./gen.sh 'InputSerifNarrow Bold Complete Mono'
./gen.sh 'InputSerifNarrow Bold Complete'
./gen.sh 'InputSerifNarrow Bold'
./gen.sh 'InputSerifNarrow Bold Complete'
./gen.sh 'InputSerifNarrow Bold'
./gen.sh 'InputSerifNarrow'
./gen.sh 'InputSerifNarrow BoldIta Complete Mono'
./gen.sh 'InputSerifNarrow BoldIta Complete'
./gen.sh 'InputSerifNarrow BoldIta'
./gen.sh 'InputSerifNarrow BoldIta Complete'
./gen.sh 'InputSerifNarrow BoldIta'
./gen.sh 'InputSerifNarrow'
./gen.sh 'InputSerifNarrow Complete Mono'
./gen.sh 'InputSerifNarrow Complete'
./gen.sh 'InputSerifNarrow'
./gen.sh 'InputSerifNarrow Complete'
./gen.sh 'InputSerifNarrow'
./gen.sh 'InputSerifNarrow'
./gen.sh 'InputSerifNarrow ExLight Complete Mono'
./gen.sh 'InputSerifNarrow ExLight Complete'
./gen.sh 'InputSerifNarrow ExLight'
./gen.sh 'InputSerifNarrow ExLight Complete'
./gen.sh 'InputSerifNarrow ExLight'
./gen.sh 'InputSerifNarrow'
./gen.sh 'InputSerifNarrow ExLightIta Complete Mono'
./gen.sh 'InputSerifNarrow ExLightIta Complete'
./gen.sh 'InputSerifNarrow ExLightIta'
./gen.sh 'InputSerifNarrow ExLightIta Complete'
./gen.sh 'InputSerifNarrow ExLightIta'
./gen.sh 'InputSerifNarrow'
./gen.sh 'InputSerifNarrow Italic Complete Mono'
./gen.sh 'InputSerifNarrow Italic Complete'
./gen.sh 'InputSerifNarrow Italic'
./gen.sh 'InputSerifNarrow Italic Complete'
./gen.sh 'InputSerifNarrow Italic'
./gen.sh 'InputSerifNarrow'
./gen.sh 'InputSerifNarrow Light Complete Mono'
./gen.sh 'InputSerifNarrow Light Complete'
./gen.sh 'InputSerifNarrow Light'
./gen.sh 'InputSerifNarrow Light Complete'
./gen.sh 'InputSerifNarrow Light'
./gen.sh 'InputSerifNarrow'
./gen.sh 'InputSerifNarrow LightIta Complete Mono'
./gen.sh 'InputSerifNarrow LightIta Complete'
./gen.sh 'InputSerifNarrow LightIta'
./gen.sh 'InputSerifNarrow LightIta Complete'
./gen.sh 'InputSerifNarrow LightIta'
./gen.sh 'InputSerifNarrow'
./gen.sh 'InputSerifNarrow Medium Complete Mono'
./gen.sh 'InputSerifNarrow Medium Complete'
./gen.sh 'InputSerifNarrow Medium'
./gen.sh 'InputSerifNarrow Medium Complete'
./gen.sh 'InputSerifNarrow Medium'
./gen.sh 'InputSerifNarrow'
./gen.sh 'InputSerifNarrow MediumIta Complete Mono'
./gen.sh 'InputSerifNarrow MediumIta Complete'
./gen.sh 'InputSerifNarrow MediumIta'
./gen.sh 'InputSerifNarrow MediumIta Complete'
./gen.sh 'InputSerifNarrow MediumIta'
./gen.sh 'InputSerifNarrow'
./gen.sh 'InputSerifNarrow Thin Complete Mono'
./gen.sh 'InputSerifNarrow Thin Complete'
./gen.sh 'InputSerifNarrow Thin'
./gen.sh 'InputSerifNarrow Thin Complete'
./gen.sh 'InputSerifNarrow Thin'
./gen.sh 'InputSerifNarrow'
./gen.sh 'InputSerifNarrow ThinIta Complete Mono'
./gen.sh 'InputSerifNarrow ThinIta Complete'
./gen.sh 'InputSerifNarrow ThinIta'
./gen.sh 'InputSerifNarrow ThinIta Complete'
./gen.sh 'InputSerifNarrow ThinIta'
./gen.sh 'InputSerifNarrow'
./gen.sh 'Knack Bold Complete Mono'
./gen.sh 'Knack Bold Complete'
./gen.sh 'Knack Bold'
./gen.sh 'Knack Bold Complete'
./gen.sh 'Knack Bold'
./gen.sh 'Knack'
./gen.sh 'Knack Bold Italic Complete Mono'
./gen.sh 'Knack Bold Italic Complete'
./gen.sh 'Knack Bold Italic'
./gen.sh 'Knack Bold Italic Complete'
./gen.sh 'Knack Bold Italic'
./gen.sh 'Knack Bold'
./gen.sh 'Knack Bold Italic Mono Complete Mono'
./gen.sh 'Knack Bold Italic Mono Complete'
./gen.sh 'Knack Bold Italic Mono'
./gen.sh 'Knack Bold Italic Mono Complete'
./gen.sh 'Knack Bold Italic Mono'
./gen.sh 'Knack Bold Italic'
./gen.sh 'Knack Bold Mono Complete Mono'
./gen.sh 'Knack Bold Mono Complete'
./gen.sh 'Knack Bold Mono'
./gen.sh 'Knack Bold Mono Complete'
./gen.sh 'Knack Bold Mono'
./gen.sh 'Knack Bold'
./gen.sh 'Knack Italic Complete Mono'
./gen.sh 'Knack Italic Complete'
./gen.sh 'Knack Italic'
./gen.sh 'Knack Italic Complete'
./gen.sh 'Knack Italic'
./gen.sh 'Knack'
./gen.sh 'Knack Italic Nerd Font Mono Complete Mono'
./gen.sh 'Knack Italic Nerd Font Mono Complete'
./gen.sh 'Knack Italic Nerd Font Mono'
./gen.sh 'Knack Italic Nerd Font Mono Complete'
./gen.sh 'Knack Italic Nerd Font Mono'
./gen.sh 'Knack Italic Nerd Font'
./gen.sh 'Knack Regular Complete Mono'
./gen.sh 'Knack Regular Complete'
./gen.sh 'Knack Regular'
./gen.sh 'Knack Regular Complete'
./gen.sh 'Knack Regular'
./gen.sh 'Knack'
./gen.sh 'Knack Regular Nerd Font Mono Complete Mono'
./gen.sh 'Knack Regular Nerd Font Mono Complete'
./gen.sh 'Knack Regular Nerd Font Mono'
./gen.sh 'Knack Regular Nerd Font Mono Complete'
./gen.sh 'Knack Regular Nerd Font Mono'
./gen.sh 'Knack Regular Nerd Font'
./gen.sh 'Lekton Complete Mono'
./gen.sh 'Lekton Complete'
./gen.sh 'Lekton'
./gen.sh 'Lekton Complete'
./gen.sh 'Lekton'
./gen.sh 'Lekton'
./gen.sh 'Lekton Nerd Font Complete Mono'
./gen.sh 'Lekton Nerd Font Complete'
./gen.sh 'Lekton Nerd Font'
./gen.sh 'Lekton Nerd Font Complete'
./gen.sh 'Lekton Nerd Font'
./gen.sh 'Lekton Nerd'
./gen.sh 'Lekton Nerd Font Mono Complete Mono'
./gen.sh 'Lekton Nerd Font Mono Complete'
./gen.sh 'Lekton Nerd Font Mono'
./gen.sh 'Lekton Nerd Font Mono Complete'
./gen.sh 'Lekton Nerd Font Mono'
./gen.sh 'Lekton Nerd Font'
./gen.sh 'Lekton-Bold Complete Mono'
./gen.sh 'Lekton-Bold Complete'
./gen.sh 'Lekton-Bold'
./gen.sh 'Lekton-Bold Complete'
./gen.sh 'Lekton-Bold'
./gen.sh 'Lekton-Bold'
./gen.sh 'Lekton-Bold Nerd Font Complete Mono'
./gen.sh 'Lekton-Bold Nerd Font Complete'
./gen.sh 'Lekton-Bold Nerd Font'
./gen.sh 'Lekton-Bold Nerd Font Complete'
./gen.sh 'Lekton-Bold Nerd Font'
./gen.sh 'Lekton-Bold Nerd'
./gen.sh 'Lekton-Bold Nerd Font Mono Complete Mono'
./gen.sh 'Lekton-Bold Nerd Font Mono Complete'
./gen.sh 'Lekton-Bold Nerd Font Mono'
./gen.sh 'Lekton-Bold Nerd Font Mono Complete'
./gen.sh 'Lekton-Bold Nerd Font Mono'
./gen.sh 'Lekton-Bold Nerd Font'
./gen.sh 'Lekton-Italic Complete Mono'
./gen.sh 'Lekton-Italic Complete'
./gen.sh 'Lekton-Italic'
./gen.sh 'Lekton-Italic Complete'
./gen.sh 'Lekton-Italic'
./gen.sh 'Lekton-Italic'
./gen.sh 'Lekton-Italic Nerd Font Complete Mono'
./gen.sh 'Lekton-Italic Nerd Font Complete'
./gen.sh 'Lekton-Italic Nerd Font'
./gen.sh 'Lekton-Italic Nerd Font Complete'
./gen.sh 'Lekton-Italic Nerd Font'
./gen.sh 'Lekton-Italic Nerd'
./gen.sh 'Lekton-Italic Nerd Font Mono Complete Mono'
./gen.sh 'Lekton-Italic Nerd Font Mono Complete'
./gen.sh 'Lekton-Italic Nerd Font Mono'
./gen.sh 'Lekton-Italic Nerd Font Mono Complete'
./gen.sh 'Lekton-Italic Nerd Font Mono'
./gen.sh 'Lekton-Italic Nerd Font'
./gen.sh 'Literation Mono Complete Mono'
./gen.sh 'Literation Mono Complete'
./gen.sh 'Literation Mono'
./gen.sh 'Literation Mono Complete'
./gen.sh 'Literation Mono'
./gen.sh 'Literation'
./gen.sh 'Literation Mono Nerd Font Mono Complete Mono'
./gen.sh 'Literation Mono Nerd Font Mono Complete'
./gen.sh 'Literation Mono Nerd Font Mono'
./gen.sh 'Literation Mono Nerd Font Mono Complete'
./gen.sh 'Literation Mono Nerd Font Mono'
./gen.sh 'Literation Mono Nerd Font'
./gen.sh 'M+ 1m bold Complete Mono'
./gen.sh 'M+ 1m bold Complete'
./gen.sh 'M+ 1m bold'
./gen.sh 'M+ 1m bold Complete'
./gen.sh 'M+ 1m bold'
./gen.sh 'M+ 1m'
./gen.sh 'M+ 1m bold Nerd Font Complete Mono'
./gen.sh 'M+ 1m bold Nerd Font Complete'
./gen.sh 'M+ 1m bold Nerd Font'
./gen.sh 'M+ 1m bold Nerd Font Complete'
./gen.sh 'M+ 1m bold Nerd Font'
./gen.sh 'M+ 1m bold Nerd'
./gen.sh 'M+ 1m bold Nerd Font Mono Complete Mono'
./gen.sh 'M+ 1m bold Nerd Font Mono Complete'
./gen.sh 'M+ 1m bold Nerd Font Mono'
./gen.sh 'M+ 1m bold Nerd Font Mono Complete'
./gen.sh 'M+ 1m bold Nerd Font Mono'
./gen.sh 'M+ 1m bold Nerd Font'
./gen.sh 'M+ 1m light Complete Mono'
./gen.sh 'M+ 1m light Complete'
./gen.sh 'M+ 1m light'
./gen.sh 'M+ 1m light Complete'
./gen.sh 'M+ 1m light'
./gen.sh 'M+ 1m'
./gen.sh 'M+ 1m light Nerd Font Complete Mono'
./gen.sh 'M+ 1m light Nerd Font Complete'
./gen.sh 'M+ 1m light Nerd Font'
./gen.sh 'M+ 1m light Nerd Font Complete'
./gen.sh 'M+ 1m light Nerd Font'
./gen.sh 'M+ 1m light Nerd'
./gen.sh 'M+ 1m light Nerd Font Mono Complete Mono'
./gen.sh 'M+ 1m light Nerd Font Mono Complete'
./gen.sh 'M+ 1m light Nerd Font Mono'
./gen.sh 'M+ 1m light Nerd Font Mono Complete'
./gen.sh 'M+ 1m light Nerd Font Mono'
./gen.sh 'M+ 1m light Nerd Font'
./gen.sh 'M+ 1m medium Complete Mono'
./gen.sh 'M+ 1m medium Complete'
./gen.sh 'M+ 1m medium'
./gen.sh 'M+ 1m medium Complete'
./gen.sh 'M+ 1m medium'
./gen.sh 'M+ 1m'
./gen.sh 'M+ 1m medium Nerd Font Complete Mono'
./gen.sh 'M+ 1m medium Nerd Font Complete'
./gen.sh 'M+ 1m medium Nerd Font'
./gen.sh 'M+ 1m medium Nerd Font Complete'
./gen.sh 'M+ 1m medium Nerd Font'
./gen.sh 'M+ 1m medium Nerd'
./gen.sh 'M+ 1m medium Nerd Font Mono Complete Mono'
./gen.sh 'M+ 1m medium Nerd Font Mono Complete'
./gen.sh 'M+ 1m medium Nerd Font Mono'
./gen.sh 'M+ 1m medium Nerd Font Mono Complete'
./gen.sh 'M+ 1m medium Nerd Font Mono'
./gen.sh 'M+ 1m medium Nerd Font'
./gen.sh 'M+ 1m regular Complete Mono'
./gen.sh 'M+ 1m regular Complete'
./gen.sh 'M+ 1m regular'
./gen.sh 'M+ 1m regular Complete'
./gen.sh 'M+ 1m regular'
./gen.sh 'M+ 1m'
./gen.sh 'M+ 1m regular Nerd Font Complete Mono'
./gen.sh 'M+ 1m regular Nerd Font Complete'
./gen.sh 'M+ 1m regular Nerd Font'
./gen.sh 'M+ 1m regular Nerd Font Complete'
./gen.sh 'M+ 1m regular Nerd Font'
./gen.sh 'M+ 1m regular Nerd'
./gen.sh 'M+ 1m regular Nerd Font Mono Complete Mono'
./gen.sh 'M+ 1m regular Nerd Font Mono Complete'
./gen.sh 'M+ 1m regular Nerd Font Mono'
./gen.sh 'M+ 1m regular Nerd Font Mono Complete'
./gen.sh 'M+ 1m regular Nerd Font Mono'
./gen.sh 'M+ 1m regular Nerd Font'
./gen.sh 'M+ 1m thin Complete Mono'
./gen.sh 'M+ 1m thin Complete'
./gen.sh 'M+ 1m thin'
./gen.sh 'M+ 1m thin Complete'
./gen.sh 'M+ 1m thin'
./gen.sh 'M+ 1m'
./gen.sh 'M+ 1m thin Nerd Font Complete Mono'
./gen.sh 'M+ 1m thin Nerd Font Complete'
./gen.sh 'M+ 1m thin Nerd Font'
./gen.sh 'M+ 1m thin Nerd Font Complete'
./gen.sh 'M+ 1m thin Nerd Font'
./gen.sh 'M+ 1m thin Nerd'
./gen.sh 'M+ 1m thin Nerd Font Mono Complete Mono'
./gen.sh 'M+ 1m thin Nerd Font Mono Complete'
./gen.sh 'M+ 1m thin Nerd Font Mono'
./gen.sh 'M+ 1m thin Nerd Font Mono Complete'
./gen.sh 'M+ 1m thin Nerd Font Mono'
./gen.sh 'M+ 1m thin Nerd Font'
./gen.sh 'Menlo Bold Italic for Nerd Font Complete Mono'
./gen.sh 'Menlo Bold Italic for Nerd Font Complete'
./gen.sh 'Menlo Bold Italic for Nerd Font'
./gen.sh 'Menlo Bold Italic for Nerd Font Complete'
./gen.sh 'Menlo Bold Italic for Nerd Font'
./gen.sh 'Menlo Bold Italic for Nerd'
./gen.sh 'Menlo Bold for Nerd Font Complete Mono'
./gen.sh 'Menlo Bold for Nerd Font Complete'
./gen.sh 'Menlo Bold for Nerd Font'
./gen.sh 'Menlo Bold for Nerd Font Complete'
./gen.sh 'Menlo Bold for Nerd Font'
./gen.sh 'Menlo Bold for Nerd'
./gen.sh 'Menlo Italic for Nerd Font Complete Mono'
./gen.sh 'Menlo Italic for Nerd Font Complete'
./gen.sh 'Menlo Italic for Nerd Font'
./gen.sh 'Menlo Italic for Nerd Font Complete'
./gen.sh 'Menlo Italic for Nerd Font'
./gen.sh 'Menlo Italic for Nerd'
./gen.sh 'Menlo Regular for Nerd Font Complete Mono'
./gen.sh 'Menlo Regular for Nerd Font Complete'
./gen.sh 'Menlo Regular for Nerd Font'
./gen.sh 'Menlo Regular for Nerd Font Complete'
./gen.sh 'Menlo Regular for Nerd Font'
./gen.sh 'Menlo Regular for Nerd'
./gen.sh 'Monoid Bold Nerd Font Complete Mono'
./gen.sh 'Monoid Bold Nerd Font Complete'
./gen.sh 'Monoid Bold Nerd Font'
./gen.sh 'Monoid Bold Nerd Font Complete'
./gen.sh 'Monoid Bold Nerd Font'
./gen.sh 'Monoid Bold Nerd'
./gen.sh 'Monoid Italic Nerd Font Complete Mono'
./gen.sh 'Monoid Italic Nerd Font Complete'
./gen.sh 'Monoid Italic Nerd Font'
./gen.sh 'Monoid Italic Nerd Font Complete'
./gen.sh 'Monoid Italic Nerd Font'
./gen.sh 'Monoid Italic Nerd'
./gen.sh 'Monoid Regular Nerd Font Complete Mono'
./gen.sh 'Monoid Regular Nerd Font Complete'
./gen.sh 'Monoid Regular Nerd Font'
./gen.sh 'Monoid Regular Nerd Font Complete'
./gen.sh 'Monoid Regular Nerd Font'
./gen.sh 'Monoid Regular Nerd'
./gen.sh 'Monoid Retina Nerd Font Complete Mono'
./gen.sh 'Monoid Retina Nerd Font Complete'
./gen.sh 'Monoid Retina Nerd Font'
./gen.sh 'Monoid Retina Nerd Font Complete'
./gen.sh 'Monoid Retina Nerd Font'
./gen.sh 'Monoid Retina Nerd'
./gen.sh 'Monoisome Regular Nerd Font Complete Mono'
./gen.sh 'Monoisome Regular Nerd Font Complete'
./gen.sh 'Monoisome Regular Nerd Font'
./gen.sh 'Monoisome Regular Nerd Font Complete'
./gen.sh 'Monoisome Regular Nerd Font'
./gen.sh 'Monoisome Regular Nerd'
./gen.sh 'MonteCarlo Fixed 12 Bold Nerd Font Complete Mono'
./gen.sh 'MonteCarlo Fixed 12 Bold Nerd Font Complete'
./gen.sh 'MonteCarlo Fixed 12 Bold Nerd Font'
./gen.sh 'MonteCarlo Fixed 12 Bold Nerd Font Complete'
./gen.sh 'MonteCarlo Fixed 12 Bold Nerd Font'
./gen.sh 'MonteCarlo Fixed 12 Bold Nerd'
./gen.sh 'MonteCarlo Fixed 12 Nerd Font Complete Mono'
./gen.sh 'MonteCarlo Fixed 12 Nerd Font Complete'
./gen.sh 'MonteCarlo Fixed 12 Nerd Font'
./gen.sh 'MonteCarlo Fixed 12 Nerd Font Complete'
./gen.sh 'MonteCarlo Fixed 12 Nerd Font'
./gen.sh 'MonteCarlo Fixed 12 Nerd'
./gen.sh 'MonteCarlo Nerd Font Complete Mono'
./gen.sh 'MonteCarlo Nerd Font Complete'
./gen.sh 'MonteCarlo Nerd Font'
./gen.sh 'MonteCarlo Nerd Font Complete'
./gen.sh 'MonteCarlo Nerd Font'
./gen.sh 'MonteCarlo Nerd'
./gen.sh 'PragmataPro Nerd Font Complete Mono'
./gen.sh 'PragmataPro Nerd Font Complete'
./gen.sh 'PragmataPro Nerd Font'
./gen.sh 'PragmataPro Nerd Font Complete'
./gen.sh 'PragmataPro Nerd Font'
./gen.sh 'PragmataPro Nerd'
./gen.sh 'ProggyCleanTT CE Complete Mono'
./gen.sh 'ProggyCleanTT CE Complete'
./gen.sh 'ProggyCleanTT CE'
./gen.sh 'ProggyCleanTT CE Complete'
./gen.sh 'ProggyCleanTT CE'
./gen.sh 'ProggyCleanTT'
./gen.sh 'ProggyCleanTT CE Nerd Font Complete Mono'
./gen.sh 'ProggyCleanTT CE Nerd Font Complete'
./gen.sh 'ProggyCleanTT CE Nerd Font'
./gen.sh 'ProggyCleanTT CE Nerd Font Complete'
./gen.sh 'ProggyCleanTT CE Nerd Font'
./gen.sh 'ProggyCleanTT CE Nerd'
./gen.sh 'ProggyCleanTT CE Nerd Font Mono Complete Mono'
./gen.sh 'ProggyCleanTT CE Nerd Font Mono Complete'
./gen.sh 'ProggyCleanTT CE Nerd Font Mono'
./gen.sh 'ProggyCleanTT CE Nerd Font Mono Complete'
./gen.sh 'ProggyCleanTT CE Nerd Font Mono'
./gen.sh 'ProggyCleanTT CE Nerd Font'
./gen.sh 'ProggyCleanTT Complete Mono'
./gen.sh 'ProggyCleanTT Complete'
./gen.sh 'ProggyCleanTT'
./gen.sh 'ProggyCleanTT Complete'
./gen.sh 'ProggyCleanTT'
./gen.sh 'ProggyCleanTT'
./gen.sh 'ProggyCleanTT Nerd Font Complete Mono'
./gen.sh 'ProggyCleanTT Nerd Font Complete'
./gen.sh 'ProggyCleanTT Nerd Font'
./gen.sh 'ProggyCleanTT Nerd Font Complete'
./gen.sh 'ProggyCleanTT Nerd Font'
./gen.sh 'ProggyCleanTT Nerd'
./gen.sh 'ProggyCleanTT Nerd Font Mono Complete Mono'
./gen.sh 'ProggyCleanTT Nerd Font Mono Complete'
./gen.sh 'ProggyCleanTT Nerd Font Mono'
./gen.sh 'ProggyCleanTT Nerd Font Mono Complete'
./gen.sh 'ProggyCleanTT Nerd Font Mono'
./gen.sh 'ProggyCleanTT Nerd Font'
./gen.sh 'Roboto Mono Bold Italic Nerd Font Complete Mono'
./gen.sh 'Roboto Mono Bold Italic Nerd Font Complete'
./gen.sh 'Roboto Mono Bold Italic Nerd Font'
./gen.sh 'Roboto Mono Bold Italic Nerd Font Complete'
./gen.sh 'Roboto Mono Bold Italic Nerd Font'
./gen.sh 'Roboto Mono Bold Italic Nerd'
./gen.sh 'Roboto Mono Bold Nerd Font Complete Mono'
./gen.sh 'Roboto Mono Bold Nerd Font Complete'
./gen.sh 'Roboto Mono Bold Nerd Font'
./gen.sh 'Roboto Mono Bold Nerd Font Complete'
./gen.sh 'Roboto Mono Bold Nerd Font'
./gen.sh 'Roboto Mono Bold Nerd'
./gen.sh 'Roboto Mono Italic Nerd Font Complete Mono'
./gen.sh 'Roboto Mono Italic Nerd Font Complete'
./gen.sh 'Roboto Mono Italic Nerd Font'
./gen.sh 'Roboto Mono Italic Nerd Font Complete'
./gen.sh 'Roboto Mono Italic Nerd Font'
./gen.sh 'Roboto Mono Italic Nerd'
./gen.sh 'Roboto Mono Light Italic Nerd Font Complete Mono'
./gen.sh 'Roboto Mono Light Italic Nerd Font Complete'
./gen.sh 'Roboto Mono Light Italic Nerd Font'
./gen.sh 'Roboto Mono Light Italic Nerd Font Complete'
./gen.sh 'Roboto Mono Light Italic Nerd Font'
./gen.sh 'Roboto Mono Light Italic Nerd'
./gen.sh 'Roboto Mono Light Nerd Font Complete Mono'
./gen.sh 'Roboto Mono Light Nerd Font Complete'
./gen.sh 'Roboto Mono Light Nerd Font'
./gen.sh 'Roboto Mono Light Nerd Font Complete'
./gen.sh 'Roboto Mono Light Nerd Font'
./gen.sh 'Roboto Mono Light Nerd'
./gen.sh 'Roboto Mono Medium Italic Nerd Font Complete Mono'
./gen.sh 'Roboto Mono Medium Italic Nerd Font Complete'
./gen.sh 'Roboto Mono Medium Italic Nerd Font'
./gen.sh 'Roboto Mono Medium Italic Nerd Font Complete'
./gen.sh 'Roboto Mono Medium Italic Nerd Font'
./gen.sh 'Roboto Mono Medium Italic Nerd'
./gen.sh 'Roboto Mono Medium Nerd Font Complete Mono'
./gen.sh 'Roboto Mono Medium Nerd Font Complete'
./gen.sh 'Roboto Mono Medium Nerd Font'
./gen.sh 'Roboto Mono Medium Nerd Font Complete'
./gen.sh 'Roboto Mono Medium Nerd Font'
./gen.sh 'Roboto Mono Medium Nerd'
./gen.sh 'Roboto Mono Nerd Font Complete Mono'
./gen.sh 'Roboto Mono Nerd Font Complete'
./gen.sh 'Roboto Mono Nerd Font'
./gen.sh 'Roboto Mono Nerd Font Complete'
./gen.sh 'Roboto Mono Nerd Font'
./gen.sh 'Roboto Mono Nerd'
./gen.sh 'Roboto Mono Thin Italic Nerd Font Complete Mono'
./gen.sh 'Roboto Mono Thin Italic Nerd Font Complete'
./gen.sh 'Roboto Mono Thin Italic Nerd Font'
./gen.sh 'Roboto Mono Thin Italic Nerd Font Complete'
./gen.sh 'Roboto Mono Thin Italic Nerd Font'
./gen.sh 'Roboto Mono Thin Italic Nerd'
./gen.sh 'Roboto Mono Thin Nerd Font Complete Mono'
./gen.sh 'Roboto Mono Thin Nerd Font Complete'
./gen.sh 'Roboto Mono Thin Nerd Font'
./gen.sh 'Roboto Mono Thin Nerd Font Complete'
./gen.sh 'Roboto Mono Thin Nerd Font'
./gen.sh 'Roboto Mono Thin Nerd'
./gen.sh 'Sauce Code Pro Black Complete Mono'
./gen.sh 'Sauce Code Pro Black Complete'
./gen.sh 'Sauce Code Pro Black'
./gen.sh 'Sauce Code Pro Black Complete'
./gen.sh 'Sauce Code Pro Black'
./gen.sh 'Sauce Code Pro'
./gen.sh 'Sauce Code Pro Black Nerd Font Mono Complete Mono'
./gen.sh 'Sauce Code Pro Black Nerd Font Mono Complete'
./gen.sh 'Sauce Code Pro Black Nerd Font Mono'
./gen.sh 'Sauce Code Pro Black Nerd Font Mono Complete'
./gen.sh 'Sauce Code Pro Black Nerd Font Mono'
./gen.sh 'Sauce Code Pro Black Nerd Font'
./gen.sh 'Sauce Code Pro Bold Complete Mono'
./gen.sh 'Sauce Code Pro Bold Complete'
./gen.sh 'Sauce Code Pro Bold'
./gen.sh 'Sauce Code Pro Bold Complete'
./gen.sh 'Sauce Code Pro Bold'
./gen.sh 'Sauce Code Pro'
./gen.sh 'Sauce Code Pro Bold Nerd Font Mono Complete Mono'
./gen.sh 'Sauce Code Pro Bold Nerd Font Mono Complete'
./gen.sh 'Sauce Code Pro Bold Nerd Font Mono'
./gen.sh 'Sauce Code Pro Bold Nerd Font Mono Complete'
./gen.sh 'Sauce Code Pro Bold Nerd Font Mono'
./gen.sh 'Sauce Code Pro Bold Nerd Font'
./gen.sh 'Sauce Code Pro Complete Mono'
./gen.sh 'Sauce Code Pro Complete'
./gen.sh 'Sauce Code Pro'
./gen.sh 'Sauce Code Pro Complete'
./gen.sh 'Sauce Code Pro'
./gen.sh 'Sauce Code'
./gen.sh 'Sauce Code Pro ExtraLight Complete Mono'
./gen.sh 'Sauce Code Pro ExtraLight Complete'
./gen.sh 'Sauce Code Pro ExtraLight'
./gen.sh 'Sauce Code Pro ExtraLight Complete'
./gen.sh 'Sauce Code Pro ExtraLight'
./gen.sh 'Sauce Code Pro'
./gen.sh 'Sauce Code Pro ExtraLight Nerd Font Mono Complete Mono'
./gen.sh 'Sauce Code Pro ExtraLight Nerd Font Mono Complete'
./gen.sh 'Sauce Code Pro ExtraLight Nerd Font Mono'
./gen.sh 'Sauce Code Pro ExtraLight Nerd Font Mono Complete'
./gen.sh 'Sauce Code Pro ExtraLight Nerd Font Mono'
./gen.sh 'Sauce Code Pro ExtraLight Nerd Font'
./gen.sh 'Sauce Code Pro Light Complete Mono'
./gen.sh 'Sauce Code Pro Light Complete'
./gen.sh 'Sauce Code Pro Light'
./gen.sh 'Sauce Code Pro Light Complete'
./gen.sh 'Sauce Code Pro Light'
./gen.sh 'Sauce Code Pro'
./gen.sh 'Sauce Code Pro Light Nerd Font Mono Complete Mono'
./gen.sh 'Sauce Code Pro Light Nerd Font Mono Complete'
./gen.sh 'Sauce Code Pro Light Nerd Font Mono'
./gen.sh 'Sauce Code Pro Light Nerd Font Mono Complete'
./gen.sh 'Sauce Code Pro Light Nerd Font Mono'
./gen.sh 'Sauce Code Pro Light Nerd Font'
./gen.sh 'Sauce Code Pro Medium Complete Mono'
./gen.sh 'Sauce Code Pro Medium Complete'
./gen.sh 'Sauce Code Pro Medium'
./gen.sh 'Sauce Code Pro Medium Complete'
./gen.sh 'Sauce Code Pro Medium'
./gen.sh 'Sauce Code Pro'
./gen.sh 'Sauce Code Pro Medium Nerd Font Mono Complete Mono'
./gen.sh 'Sauce Code Pro Medium Nerd Font Mono Complete'
./gen.sh 'Sauce Code Pro Medium Nerd Font Mono'
./gen.sh 'Sauce Code Pro Medium Nerd Font Mono Complete'
./gen.sh 'Sauce Code Pro Medium Nerd Font Mono'
./gen.sh 'Sauce Code Pro Medium Nerd Font'
./gen.sh 'Sauce Code Pro Semibold Complete Mono'
./gen.sh 'Sauce Code Pro Semibold Complete'
./gen.sh 'Sauce Code Pro Semibold'
./gen.sh 'Sauce Code Pro Semibold Complete'
./gen.sh 'Sauce Code Pro Semibold'
./gen.sh 'Sauce Code Pro'
./gen.sh 'Sauce Code Pro Semibold Nerd Font Mono Complete Mono'
./gen.sh 'Sauce Code Pro Semibold Nerd Font Mono Complete'
./gen.sh 'Sauce Code Pro Semibold Nerd Font Mono'
./gen.sh 'Sauce Code Pro Semibold Nerd Font Mono Complete'
./gen.sh 'Sauce Code Pro Semibold Nerd Font Mono'
./gen.sh 'Sauce Code Pro Semibold Nerd Font'
./gen.sh 'Source Code Pro Black Nerd Font Complete Mono'
./gen.sh 'Source Code Pro Black Nerd Font Complete'
./gen.sh 'Source Code Pro Black Nerd Font'
./gen.sh 'Source Code Pro Black Nerd Font Complete'
./gen.sh 'Source Code Pro Black Nerd Font'
./gen.sh 'Source Code Pro Black Nerd'
./gen.sh 'Source Code Pro Bold Nerd Font Complete Mono'
./gen.sh 'Source Code Pro Bold Nerd Font Complete'
./gen.sh 'Source Code Pro Bold Nerd Font'
./gen.sh 'Source Code Pro Bold Nerd Font Complete'
./gen.sh 'Source Code Pro Bold Nerd Font'
./gen.sh 'Source Code Pro Bold Nerd'
./gen.sh 'Source Code Pro ExtraLight Complete Mono'
./gen.sh 'Source Code Pro ExtraLight Complete'
./gen.sh 'Source Code Pro ExtraLight'
./gen.sh 'Source Code Pro ExtraLight Complete'
./gen.sh 'Source Code Pro ExtraLight'
./gen.sh 'Source Code Pro'
./gen.sh 'monofur  bold for Complete Mono'
./gen.sh 'monofur  bold for Complete'
./gen.sh 'monofur  bold for'
./gen.sh 'monofur  bold for Complete'
./gen.sh 'monofur  bold for'
./gen.sh 'monofur  bold'
./gen.sh 'monofur  bold for Nerd Font Mono Complete Mono'
./gen.sh 'monofur  bold for Nerd Font Mono Complete'
./gen.sh 'monofur  bold for Nerd Font Mono'
./gen.sh 'monofur  bold for Nerd Font Mono Complete'
./gen.sh 'monofur  bold for Nerd Font Mono'
./gen.sh 'monofur  bold for Nerd Font'
./gen.sh 'monofur  italic for Complete Mono'
./gen.sh 'monofur  italic for Complete'
./gen.sh 'monofur  italic for'
./gen.sh 'monofur  italic for Complete'
./gen.sh 'monofur  italic for'
./gen.sh 'monofur  italic'
./gen.sh 'monofur  italic for Nerd Font Mono Complete Mono'
./gen.sh 'monofur  italic for Nerd Font Mono Complete'
./gen.sh 'monofur  italic for Nerd Font Mono'
./gen.sh 'monofur  italic for Nerd Font Mono Complete'
./gen.sh 'monofur  italic for Nerd Font Mono'
./gen.sh 'monofur  italic for Nerd Font'
./gen.sh 'monofur for Complete Mono'
./gen.sh 'monofur for Complete'
./gen.sh 'monofur for'
./gen.sh 'monofur for Complete'
./gen.sh 'monofur for'
./gen.sh 'monofur'
./gen.sh 'monofur for Nerd Font Mono Complete Mono'
./gen.sh 'monofur for Nerd Font Mono Complete'
./gen.sh 'monofur for Nerd Font Mono'
./gen.sh 'monofur for Nerd Font Mono Complete'
./gen.sh 'monofur for Nerd Font Mono'
./gen.sh 'monofur for Nerd Font'
./gen.sh '3270 Narrow Complete Mono'
./gen.sh '3270 Narrow Complete'
./gen.sh '3270 Narrow'
./gen.sh '3270 Narrow Complete'
./gen.sh '3270 Narrow'
./gen.sh '3270'
./gen.sh '3270 Narrow Mono Complete Mono'
./gen.sh '3270 Narrow Mono Complete'
./gen.sh '3270 Narrow Mono'
./gen.sh '3270 Narrow Mono Complete'
./gen.sh '3270 Narrow Mono'
./gen.sh '3270 Narrow'
./gen.sh '3270-Medium Complete Mono'
./gen.sh '3270-Medium Complete'
./gen.sh '3270-Medium'
./gen.sh '3270-Medium Complete'
./gen.sh '3270-Medium'
./gen.sh '3270-Medium'
./gen.sh '3270-Medium Mono Complete Mono'
./gen.sh '3270-Medium Mono Complete'
./gen.sh '3270-Medium Mono'
./gen.sh '3270-Medium Mono Complete'
./gen.sh '3270-Medium Mono'
./gen.sh '3270-Medium'
./gen.sh 'AurulentSansMono-Regular Complete Mono'
./gen.sh 'AurulentSansMono-Regular Complete'
./gen.sh 'AurulentSansMono-Regular'
./gen.sh 'AurulentSansMono-Regular Complete'
./gen.sh 'AurulentSansMono-Regular'
./gen.sh 'AurulentSansMono-Regular'
./gen.sh 'AurulentSansMono-Regular Mono Complete Mono'
./gen.sh 'AurulentSansMono-Regular Mono Complete'
./gen.sh 'AurulentSansMono-Regular Mono'
./gen.sh 'AurulentSansMono-Regular Mono Complete'
./gen.sh 'AurulentSansMono-Regular Mono'
./gen.sh 'AurulentSansMono-Regular'
./gen.sh 'Droid Sans Mono Complete Mono'
./gen.sh 'Droid Sans Mono Complete'
./gen.sh 'Droid Sans Mono'
./gen.sh 'Droid Sans Mono Complete'
./gen.sh 'Droid Sans Mono'
./gen.sh 'Droid Sans'
./gen.sh 'Droid Sans Mono Mono Complete Mono'
./gen.sh 'Droid Sans Mono Mono Complete'
./gen.sh 'Droid Sans Mono Mono'
./gen.sh 'Droid Sans Mono Mono Complete'
./gen.sh 'Droid Sans Mono Mono'
./gen.sh 'Droid Sans Mono'
./gen.sh 'Fira Code Bold Complete Mono'
./gen.sh 'Fira Code Bold Complete'
./gen.sh 'Fira Code Bold'
./gen.sh 'Fira Code Bold Complete'
./gen.sh 'Fira Code Bold'
./gen.sh 'Fira Code'
./gen.sh 'Fira Code Light Complete Mono'
./gen.sh 'Fira Code Light Complete'
./gen.sh 'Fira Code Light'
./gen.sh 'Fira Code Light Complete'
./gen.sh 'Fira Code Light'
./gen.sh 'Fira Code'
./gen.sh 'Fira Code Medium Complete Mono'
./gen.sh 'Fira Code Medium Complete'
./gen.sh 'Fira Code Medium'
./gen.sh 'Fira Code Medium Complete'
./gen.sh 'Fira Code Medium'
./gen.sh 'Fira Code'
./gen.sh 'Fira Code Regular Complete Mono'
./gen.sh 'Fira Code Regular Complete'
./gen.sh 'Fira Code Regular'
./gen.sh 'Fira Code Regular Complete'
./gen.sh 'Fira Code Regular'
./gen.sh 'Fira Code'
./gen.sh 'Fira Code Retina Complete Mono'
./gen.sh 'Fira Code Retina Complete'
./gen.sh 'Fira Code Retina'
./gen.sh 'Fira Code Retina Complete'
./gen.sh 'Fira Code Retina'
./gen.sh 'Fira Code'
./gen.sh 'Fura Mono Bold Complete Mono'
./gen.sh 'Fura Mono Bold Complete'
./gen.sh 'Fura Mono Bold'
./gen.sh 'Fura Mono Bold Complete'
./gen.sh 'Fura Mono Bold'
./gen.sh 'Fura Mono'
./gen.sh 'Fura Mono Bold Mono Complete Mono'
./gen.sh 'Fura Mono Bold Mono Complete'
./gen.sh 'Fura Mono Bold Mono'
./gen.sh 'Fura Mono Bold Mono Complete'
./gen.sh 'Fura Mono Bold Mono'
./gen.sh 'Fura Mono Bold'
./gen.sh 'Fura Mono Medium Complete Mono'
./gen.sh 'Fura Mono Medium Complete'
./gen.sh 'Fura Mono Medium'
./gen.sh 'Fura Mono Medium Complete'
./gen.sh 'Fura Mono Medium'
./gen.sh 'Fura Mono'
./gen.sh 'Fura Mono Medium Mono Complete Mono'
./gen.sh 'Fura Mono Medium Mono Complete'
./gen.sh 'Fura Mono Medium Mono'
./gen.sh 'Fura Mono Medium Mono Complete'
./gen.sh 'Fura Mono Medium Mono'
./gen.sh 'Fura Mono Medium'
./gen.sh 'Fura Mono Regular Complete Mono'
./gen.sh 'Fura Mono Regular Complete'
./gen.sh 'Fura Mono Regular'
./gen.sh 'Fura Mono Regular Complete'
./gen.sh 'Fura Mono Regular'
./gen.sh 'Fura Mono'
./gen.sh 'Fura Mono Regular Mono Complete Mono'
./gen.sh 'Fura Mono Regular Mono Complete'
./gen.sh 'Fura Mono Regular Mono'
./gen.sh 'Fura Mono Regular Mono Complete'
./gen.sh 'Fura Mono Regular Mono'
./gen.sh 'Fura Mono Regular'
./gen.sh 'Hasklig Black Complete Mono'
./gen.sh 'Hasklig Black Complete'
./gen.sh 'Hasklig Black'
./gen.sh 'Hasklig Black Complete'
./gen.sh 'Hasklig Black'
./gen.sh 'Hasklig'
./gen.sh 'Hasklig Black Italic Complete Mono'
./gen.sh 'Hasklig Black Italic Complete'
./gen.sh 'Hasklig Black Italic'
./gen.sh 'Hasklig Black Italic Complete'
./gen.sh 'Hasklig Black Italic'
./gen.sh 'Hasklig Black'
./gen.sh 'Hasklig Bold Complete Mono'
./gen.sh 'Hasklig Bold Complete'
./gen.sh 'Hasklig Bold'
./gen.sh 'Hasklig Bold Complete'
./gen.sh 'Hasklig Bold'
./gen.sh 'Hasklig'
./gen.sh 'Hasklig Bold Italic Complete Mono'
./gen.sh 'Hasklig Bold Italic Complete'
./gen.sh 'Hasklig Bold Italic'
./gen.sh 'Hasklig Bold Italic Complete'
./gen.sh 'Hasklig Bold Italic'
./gen.sh 'Hasklig Bold'
./gen.sh 'Hasklig Complete Mono'
./gen.sh 'Hasklig Complete'
./gen.sh 'Hasklig'
./gen.sh 'Hasklig Complete'
./gen.sh 'Hasklig'
./gen.sh 'Hasklig'
./gen.sh 'Hasklig ExtraLight Complete Mono'
./gen.sh 'Hasklig ExtraLight Complete'
./gen.sh 'Hasklig ExtraLight'
./gen.sh 'Hasklig ExtraLight Complete'
./gen.sh 'Hasklig ExtraLight'
./gen.sh 'Hasklig'
./gen.sh 'Hasklig ExtraLight Italic Complete Mono'
./gen.sh 'Hasklig ExtraLight Italic Complete'
./gen.sh 'Hasklig ExtraLight Italic'
./gen.sh 'Hasklig ExtraLight Italic Complete'
./gen.sh 'Hasklig ExtraLight Italic'
./gen.sh 'Hasklig ExtraLight'
./gen.sh 'Hasklig Italic Complete Mono'
./gen.sh 'Hasklig Italic Complete'
./gen.sh 'Hasklig Italic'
./gen.sh 'Hasklig Italic Complete'
./gen.sh 'Hasklig Italic'
./gen.sh 'Hasklig'
./gen.sh 'Hasklig Light Complete Mono'
./gen.sh 'Hasklig Light Complete'
./gen.sh 'Hasklig Light'
./gen.sh 'Hasklig Light Complete'
./gen.sh 'Hasklig Light'
./gen.sh 'Hasklig'
./gen.sh 'Hasklig Light Italic Complete Mono'
./gen.sh 'Hasklig Light Italic Complete'
./gen.sh 'Hasklig Light Italic'
./gen.sh 'Hasklig Light Italic Complete'
./gen.sh 'Hasklig Light Italic'
./gen.sh 'Hasklig Light'
./gen.sh 'Hasklig Medium Complete Mono'
./gen.sh 'Hasklig Medium Complete'
./gen.sh 'Hasklig Medium'
./gen.sh 'Hasklig Medium Complete'
./gen.sh 'Hasklig Medium'
./gen.sh 'Hasklig'
./gen.sh 'Hasklig Medium Italic Complete Mono'
./gen.sh 'Hasklig Medium Italic Complete'
./gen.sh 'Hasklig Medium Italic'
./gen.sh 'Hasklig Medium Italic Complete'
./gen.sh 'Hasklig Medium Italic'
./gen.sh 'Hasklig Medium'
./gen.sh 'Hasklig Semibold Complete Mono'
./gen.sh 'Hasklig Semibold Complete'
./gen.sh 'Hasklig Semibold'
./gen.sh 'Hasklig Semibold Complete'
./gen.sh 'Hasklig Semibold'
./gen.sh 'Hasklig'
./gen.sh 'Hasklig Semibold Italic Complete Mono'
./gen.sh 'Hasklig Semibold Italic Complete'
./gen.sh 'Hasklig Semibold Italic'
./gen.sh 'Hasklig Semibold Italic Complete'
./gen.sh 'Hasklig Semibold Italic'
./gen.sh 'Hasklig Semibold'
./gen.sh 'Hermit Bold Complete Mono'
./gen.sh 'Hermit Bold Complete'
./gen.sh 'Hermit Bold'
./gen.sh 'Hermit Bold Complete'
./gen.sh 'Hermit Bold'
./gen.sh 'Hermit'
./gen.sh 'Hermit Light Complete Mono'
./gen.sh 'Hermit Light Complete'
./gen.sh 'Hermit Light'
./gen.sh 'Hermit Light Complete'
./gen.sh 'Hermit Light'
./gen.sh 'Hermit'
./gen.sh 'Hermit Medium Complete Mono'
./gen.sh 'Hermit Medium Complete'
./gen.sh 'Hermit Medium'
./gen.sh 'Hermit Medium Complete'
./gen.sh 'Hermit Medium'
./gen.sh 'Hermit'
./gen.sh 'Hurmit Bold Complete Mono'
./gen.sh 'Hurmit Bold Complete'
./gen.sh 'Hurmit Bold'
./gen.sh 'Hurmit Bold Complete'
./gen.sh 'Hurmit Bold'
./gen.sh 'Hurmit'
./gen.sh 'Hurmit Bold Mono Complete Mono'
./gen.sh 'Hurmit Bold Mono Complete'
./gen.sh 'Hurmit Bold Mono'
./gen.sh 'Hurmit Bold Mono Complete'
./gen.sh 'Hurmit Bold Mono'
./gen.sh 'Hurmit Bold'
./gen.sh 'Hurmit Light Complete Mono'
./gen.sh 'Hurmit Light Complete'
./gen.sh 'Hurmit Light'
./gen.sh 'Hurmit Light Complete'
./gen.sh 'Hurmit Light'
./gen.sh 'Hurmit'
./gen.sh 'Hurmit Light Mono Complete Mono'
./gen.sh 'Hurmit Light Mono Complete'
./gen.sh 'Hurmit Light Mono'
./gen.sh 'Hurmit Light Mono Complete'
./gen.sh 'Hurmit Light Mono'
./gen.sh 'Hurmit Light'
./gen.sh 'Hurmit Medium Complete Mono'
./gen.sh 'Hurmit Medium Complete'
./gen.sh 'Hurmit Medium'
./gen.sh 'Hurmit Medium Complete'
./gen.sh 'Hurmit Medium'
./gen.sh 'Hurmit'
./gen.sh 'Hurmit Medium Mono Complete Mono'
./gen.sh 'Hurmit Medium Mono Complete'
./gen.sh 'Hurmit Medium Mono'
./gen.sh 'Hurmit Medium Mono Complete'
./gen.sh 'Hurmit Medium Mono'
./gen.sh 'Hurmit Medium'
./gen.sh 'Inconsolata for Complete Mono'
./gen.sh 'Inconsolata for Complete'
./gen.sh 'Inconsolata for'
./gen.sh 'Inconsolata for Complete'
./gen.sh 'Inconsolata for'
./gen.sh 'Inconsolata'
./gen.sh 'Inconsolata for Mono Complete Mono'
./gen.sh 'Inconsolata for Mono Complete'
./gen.sh 'Inconsolata for Mono'
./gen.sh 'Inconsolata for Mono Complete'
./gen.sh 'Inconsolata for Mono'
./gen.sh 'Inconsolata for'
./gen.sh 'Meslo LG L DZ Regular for Complete Mono'
./gen.sh 'Meslo LG L DZ Regular for Complete'
./gen.sh 'Meslo LG L DZ Regular for'
./gen.sh 'Meslo LG L DZ Regular for Complete'
./gen.sh 'Meslo LG L DZ Regular for'
./gen.sh 'Meslo LG L DZ Regular'
./gen.sh 'Meslo LG L DZ Regular for Nerd Font Mono Complete Mono'
./gen.sh 'Meslo LG L DZ Regular for Nerd Font Mono Complete'
./gen.sh 'Meslo LG L DZ Regular for Nerd Font Mono'
./gen.sh 'Meslo LG L DZ Regular for Nerd Font Mono Complete'
./gen.sh 'Meslo LG L DZ Regular for Nerd Font Mono'
./gen.sh 'Meslo LG L DZ Regular for Nerd Font'
./gen.sh 'Meslo LG L Regular for Complete Mono'
./gen.sh 'Meslo LG L Regular for Complete'
./gen.sh 'Meslo LG L Regular for'
./gen.sh 'Meslo LG L Regular for Complete'
./gen.sh 'Meslo LG L Regular for'
./gen.sh 'Meslo LG L Regular'
./gen.sh 'Meslo LG L Regular for Nerd Font Mono Complete Mono'
./gen.sh 'Meslo LG L Regular for Nerd Font Mono Complete'
./gen.sh 'Meslo LG L Regular for Nerd Font Mono'
./gen.sh 'Meslo LG L Regular for Nerd Font Mono Complete'
./gen.sh 'Meslo LG L Regular for Nerd Font Mono'
./gen.sh 'Meslo LG L Regular for Nerd Font'
./gen.sh 'Meslo LG M DZ Regular for Complete Mono'
./gen.sh 'Meslo LG M DZ Regular for Complete'
./gen.sh 'Meslo LG M DZ Regular for'
./gen.sh 'Meslo LG M DZ Regular for Complete'
./gen.sh 'Meslo LG M DZ Regular for'
./gen.sh 'Meslo LG M DZ Regular'
./gen.sh 'Meslo LG M DZ Regular for Nerd Font Mono Complete Mono'
./gen.sh 'Meslo LG M DZ Regular for Nerd Font Mono Complete'
./gen.sh 'Meslo LG M DZ Regular for Nerd Font Mono'
./gen.sh 'Meslo LG M DZ Regular for Nerd Font Mono Complete'
./gen.sh 'Meslo LG M DZ Regular for Nerd Font Mono'
./gen.sh 'Meslo LG M DZ Regular for Nerd Font'
./gen.sh 'Meslo LG M Regular for Complete Mono'
./gen.sh 'Meslo LG M Regular for Complete'
./gen.sh 'Meslo LG M Regular for'
./gen.sh 'Meslo LG M Regular for Complete'
./gen.sh 'Meslo LG M Regular for'
./gen.sh 'Meslo LG M Regular'
./gen.sh 'Meslo LG M Regular for Nerd Font Mono Complete Mono'
./gen.sh 'Meslo LG M Regular for Nerd Font Mono Complete'
./gen.sh 'Meslo LG M Regular for Nerd Font Mono'
./gen.sh 'Meslo LG M Regular for Nerd Font Mono Complete'
./gen.sh 'Meslo LG M Regular for Nerd Font Mono'
./gen.sh 'Meslo LG M Regular for Nerd Font'
./gen.sh 'Meslo LG S DZ Regular for Complete Mono'
./gen.sh 'Meslo LG S DZ Regular for Complete'
./gen.sh 'Meslo LG S DZ Regular for'
./gen.sh 'Meslo LG S DZ Regular for Complete'
./gen.sh 'Meslo LG S DZ Regular for'
./gen.sh 'Meslo LG S DZ Regular'
./gen.sh 'Meslo LG S DZ Regular for Nerd Font Mono Complete Mono'
./gen.sh 'Meslo LG S DZ Regular for Nerd Font Mono Complete'
./gen.sh 'Meslo LG S DZ Regular for Nerd Font Mono'
./gen.sh 'Meslo LG S DZ Regular for Nerd Font Mono Complete'
./gen.sh 'Meslo LG S DZ Regular for Nerd Font Mono'
./gen.sh 'Meslo LG S DZ Regular for Nerd Font'
./gen.sh 'Meslo LG S Regular for Complete Mono'
./gen.sh 'Meslo LG S Regular for Complete'
./gen.sh 'Meslo LG S Regular for'
./gen.sh 'Meslo LG S Regular for Complete'
./gen.sh 'Meslo LG S Regular for'
./gen.sh 'Meslo LG S Regular'
./gen.sh 'Meslo LG S Regular for Nerd Font Mono Complete Mono'
./gen.sh 'Meslo LG S Regular for Nerd Font Mono Complete'
./gen.sh 'Meslo LG S Regular for Nerd Font Mono'
./gen.sh 'Meslo LG S Regular for Nerd Font Mono Complete'
./gen.sh 'Meslo LG S Regular for Nerd Font Mono'
./gen.sh 'Meslo LG S Regular for Nerd Font'
./gen.sh 'Source Code Pro Black Italic Nerd Font Complete Mono'
./gen.sh 'Source Code Pro Black Italic Nerd Font Complete'
./gen.sh 'Source Code Pro Black Italic Nerd Font'
./gen.sh 'Source Code Pro Black Italic Nerd Font Complete'
./gen.sh 'Source Code Pro Black Italic Nerd Font'
./gen.sh 'Source Code Pro Black Italic Nerd'
./gen.sh 'Source Code Pro Black Nerd Font Complete Mono'
./gen.sh 'Source Code Pro Black Nerd Font Complete'
./gen.sh 'Source Code Pro Black Nerd Font'
./gen.sh 'Source Code Pro Black Nerd Font Complete'
./gen.sh 'Source Code Pro Black Nerd Font'
./gen.sh 'Source Code Pro Black Nerd'
./gen.sh 'Source Code Pro Bold Italic Nerd Font Complete Mono'
./gen.sh 'Source Code Pro Bold Italic Nerd Font Complete'
./gen.sh 'Source Code Pro Bold Italic Nerd Font'
./gen.sh 'Source Code Pro Bold Italic Nerd Font Complete'
./gen.sh 'Source Code Pro Bold Italic Nerd Font'
./gen.sh 'Source Code Pro Bold Italic Nerd'
./gen.sh 'Source Code Pro Bold Nerd Font Complete Mono'
./gen.sh 'Source Code Pro Bold Nerd Font Complete'
./gen.sh 'Source Code Pro Bold Nerd Font'
./gen.sh 'Source Code Pro Bold Nerd Font Complete'
./gen.sh 'Source Code Pro Bold Nerd Font'
./gen.sh 'Source Code Pro Bold Nerd'
./gen.sh 'Source Code Pro ExtraLight Italic Complete Mono'
./gen.sh 'Source Code Pro ExtraLight Italic Complete'
./gen.sh 'Source Code Pro ExtraLight Italic'
./gen.sh 'Source Code Pro ExtraLight Italic Complete'
./gen.sh 'Source Code Pro ExtraLight Italic'
./gen.sh 'Source Code Pro ExtraLight'
./gen.sh 'Source Code Pro ExtraLight Nerd Font Complete Mono'
./gen.sh 'Source Code Pro ExtraLight Nerd Font Complete'
./gen.sh 'Source Code Pro ExtraLight Nerd Font'
./gen.sh 'Source Code Pro ExtraLight Nerd Font Complete'
./gen.sh 'Source Code Pro ExtraLight Nerd Font'
./gen.sh 'Source Code Pro ExtraLight Nerd'
./gen.sh 'Source Code Pro Italic Complete Mono'
./gen.sh 'Source Code Pro Italic Complete'
./gen.sh 'Source Code Pro Italic'
./gen.sh 'Source Code Pro Italic Complete'
./gen.sh 'Source Code Pro Italic'
./gen.sh 'Source Code Pro'
./gen.sh 'Source Code Pro Light Complete'
./gen.sh 'Source Code Pro Light'
./gen.sh 'Source Code Pro'
